### ISSUE TITLE
"Alle Versprechen" Seite in Navi

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#103]
Wir haben eine Übersichtsseite vergessen, die alle aktiven Versprechen, sortiert nach den neuesten zuerst, anzeigt.

In der Hauptnavi sollte es dazu den Punkt "Alle Versprechen" zwichen "Ich versprech' s" und "So funktioniert`s" geben.

Die Seite gibt es ja schon, muss nur noch in die Navi: https://beta.buntundverbindlich.de/de/pledges/
Müsste aber überarbeitet werden, so dass sie alle Versprechen (ohne den Header "die neuesten Versprechen"), sortiert nach Ablaufdatum, absteigend (aktive zuerst, abgelaufene zuletzt) mit Paginierung anzeigt.

**Comment by marcaltmann** [comment]
Sollte das Verhalten nicht übereinstimmen mit der "leeren Suche", also wenn ich ins Suchfeld gar nichts eingebe und Suchen klicke? Dann würde ich die Versprechensübersicht mit der Unterteilung lieber ganz aus der Suchseite rausnehmen.

Ich baue "Alle Versprechen" mal ein, aber wir haben eigentlich jetzt schon zu wenig Platz im der Navi.

**Comment by annakress** [comment]
Ja, es ist nicht mehr viel Platz, aber es muss schon als Punkt in die Hautpnavi rein, da hilft nix. Für den Oktoberstart wird der Punkt Presse noch auskommentiert, ist für mich eh ein Kandidat, woanders hin zu wandern (z.B als Unterpunkt von Unter uns). Muss aber S. entscheiden.

Ja, das stimmt, macht Sinn, die gleiche Seite wie bei der leeren Suche zu haben. Dann gerne die Unterteilung weglassen. Irgendwann (wenn Hunderte von Pledges auf der Seite sind, aber das wird schon noch dauern) brauchen wir dann eine Sortierung und Filterung, aber ich denke nicht, dass das bis Ende des Jahres relevant ist.

**Comment by marcaltmann** [comment]
Außerdem:
- I18n und Pluralisierung für Sucherergebnis-Text
- Abstand von h1 zu Header stimmt nicht.

**Comment by marcaltmann** [comment]
Zeigt jetzt alle Versprechen sortiert nach Deadline an.
