### ISSUE TITLE
Unterschriften: Unternehmen + Ansprechpartner nicht angezeigt

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#105]
Wenn ich in dem Unterschriftenformular mein Unternehmen/Organisation angebe, erscheinen diese nicht.

Soll-Zustand: Siehe Mockup:

![signature](https://cloud.githubusercontent.com/assets/2988567/17666488/aa7999f6-6300-11e6-930e-5a5126349024.png)

**Comment by annakress** [comment]
Ist der Code noch nicht eingecheckt? Bei mir wird weiterhin nichts angezeigt.

**Comment by marcaltmann** [comment]
Doch, das Formular funktioniert offenbar noch nicht. Siehe #130. Wenn die Felder in der Datenbank gesetzt sind, sollte es funktionieren.

**Comment by marcaltmann** [comment]
Unternehmen sollte jetzt funktionieren.
