### ISSUE TITLE
OpenSans-Font verwenden

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#111]

**Comment by marcaltmann** [comment]
Ich habe jetzt drei Open-Sans-Schriftarten verwendet: Regular, Bold, Regular Italic. Tino hat allerdings in den Designs zwei verschiedene fette Schriftarten drin, Semibold und Bold. Deshalb sehen die Tage in den Kacheln etwas fetter aus jetzt.

**Comment by annakress** [comment]
Danke, das hat auch die verschobenen Kommas im Formular /pledges/new behoben.
