### ISSUE TITLE
Mehrere Tags im Pledge Formular werden nicht übernommen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#124]
1) Wenn ich über das Pledge-Formular ein Versprechen mit mehr als 1 Tag erstelle, wird in der Vorschau und allen weiteren Schritten nur der erste Tag angezeigt.

Erzeugt man dagen den Pledge über seeds.rb, scheint es zu funktionieren..

2) Eventuell damit zusammenhängend?

Browser: Chrome auf Linux.

Wenn ich im Profil eine Kachel mit Tag sehe, und dann auf Mein Konto klicke, damit das Menü dort ausklappt, verschwindet der Tag, siehe Bild:

![bug](https://cloud.githubusercontent.com/assets/2988567/17744893/ffea8814-64a9-11e6-82c2-b21da294e854.png)

**Comment by marcaltmann** [comment]
Stehen die Tags oder Tag-Ids für den Pledge denn in der Datenbank?

**Comment by annakress** [comment]
Ja, ich habe sie zu seeds.rb hinzugefügt.

**Comment by marcaltmann** [comment]
Die Zuweisung der tag_ids im Rails-Controller bzw. über tag_ids= klappt nicht, weil tag_ids nur ein String ist und kein Array.

**Comment by marcaltmann** [comment]
1 ist behoben.
@KonstantinKo kannst du dir bitte nochmal den PledgesController ansehen, und zwar pledge_params? Ich splitte da die Tags in ein Array.

**Comment by annakress** [comment]
Für mich ist 1) auch behoben. Soll das Ticket Konstantin assigned werden?

Ich lagere 2 dann in ein eigenes Ticket aus.

**Comment by marcaltmann** [comment]
Ja, @KonstantinKo bitte nochmal ansehen ob die Lösung so geht, Tests würde ich dann nachziehen.

**Comment by annakress** [comment]
ich verschieb das ticket mal nach todo, scheint ja noch nicht fertig zu sein.

**Comment by marcaltmann** [comment]
Tests nachziehen
