### ISSUE TITLE
Checkboxen funktionieren nicht in Ajax-Formularen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#130]
z.B. anonym, Organisation usw.

**Comment by marcaltmann** [comment]
Checkbox-Werte werden nicht übernommen. jQuerys val()-Funktion wird verwendet, diese gibt aber by design nicht den Checkbox-Wert zurück.

**Comment by KonstantinKo** [comment]
Checkboxen funktionieren jetzt von JS-Seite aus, aber unser custom styling scheint nicht mitzuziehen - also wenn die checkbox die auf display:none gesetzt wurde checked ist, sieht das für den Nutzer noch nicht so aus

**Comment by KonstantinKo** [comment]
![d21-checkbox-bug](https://cloud.githubusercontent.com/assets/779660/17892439/94ba9b0a-6941-11e6-848c-8ef19509eccc.gif)
