### ISSUE TITLE
Fehlende Texte auf Production

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#136]
z.b. hier werden texte (versprechenstext / button beschriftung für entwurf speichern) nicht angezeigt:

https://beta.buntundverbindlich.de/de/pledges/new

**Comment by KonstantinKo** [comment]
Sollte jetzt wieder gehen. Sprockets hat uns auf production die JS-Dateien nochmal uglified und dadurch konnten wir nichtmehr so wie vorher auf Funktionsnamen zugreifen. Hab mangle jetzt ausgestellt. Die Dateigröße hat sich dadurch leider etwas erhöht
