### ISSUE TITLE
Production - Versprechen einstellen geht nicht

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#140]
Will ich auf https://beta.buntundverbindlich.de/de/pledges/new ein Versprechen einstellen, und klicke auf den Vorschau-Button passiert nix.

**Comment by annakress** [comment]
Ist vielleicht der Mailserver nicht richtig konfiguriert?

**Comment by KonstantinKo** [comment]
Ja es war der Emailserver. Und ein Haufen anderer Email-related Dinge
