### ISSUE TITLE
Freischaltungsemail gehen nicht an redaktion@

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#144]
Vermutlich ist noch nicht die richtige Adresse eingetragen?

Für die Admin-Emails sollte redaktion@buntundverbindlich.de eingetragen werden.

**Comment by KonstantinKo** [comment]
Reden wir von Freischaltung von Nutzern oder Versprechen?

**Comment by annakress** [comment]
ich glaube da ist fälschlicherweise webadmin eingetragen:

![email](https://cloud.githubusercontent.com/assets/2988567/17901365/56f7431e-6963-11e6-9ee4-c5870eb57ecf.png)

**Comment by annakress** [comment]
sollte von redaktion@ an redaktion@ sein.

**Comment by KonstantinKo** [comment]
Die Email geht an die Emailadresse vom ersten AdminUser. Kann das natürlich auf redaktion@ ändern - oder so dass es jeder AdminUser bekommt

**Comment by annakress** [comment]
an redaktion@ reicht völlig aus. den webadmin habe ich nur für die freischaltung de ssl-zertifikats angelegt.
