### ISSUE TITLE
Rückfrage Email wird 2xverschickt + CC nicht korrekt

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#148]
Wenn ich als Initiator eine Rückfrage von einem anderen Nutzer erhalte, bekomme ich die Email dazu 2x zugeschickt.

Zudem scheint die CC Email , die an die Redaktion gehen sollte, an stefanie.kaste zu gehen (evenutell sind das aber Weiterleitungen, ist mir unklar):

This is the mail system at host mail.greensta.de.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<stefanie.kaste@buntundverbindlich.de>: host
    mail.buntundverbindlich.de[212.8.207.202] said: 550 5.1.1
    <stefanie.kaste@buntundverbindlich.de>: Recipient address rejected: User
    unknown in virtual mailbox table (in reply to RCPT TO command)
Reporting-MTA: dns; mail.greensta.de
X-Postfix-Queue-ID: 01D78B80E6
X-Postfix-Sender: rfc822; redaktion@buntundverbindlich.de
Arrival-Date: Tue, 23 Aug 2016 20:23:10 +0200 (CEST)

Final-Recipient: rfc822; stefanie.kaste@buntundverbindlich.de
Original-Recipient: rfc822;stefanie.kaste@buntundverbindlich.de
Action: failed
Status: 5.1.1
Remote-MTA: dns; mail.buntundverbindlich.de
Diagnostic-Code: smtp; 550 5.1.1 <stefanie.kaste@buntundverbindlich.de>:
    Recipient address rejected: User unknown in virtual mailbox table
Betreff	Rückfrage zu Ihrem Versprechen
Von	redaktion@buntundverbindlich.de
An	anna.fischer@7unicorns.de
Datum	Heute 20:23
Liebe/r Herr/Frau Anna Fischer

Ein Nutzer hat soeben eine Rückfrage zu Ihrem Versprechen gestellt.

Zum Beantworten der Rückfrage loggen Sie sich bitte ein und rufen Ihr Versprechen auf:
http://beta.buntundverbindlich.de/de/pledges/10

Mit besten Grüßen,
Ihre bunt und verbindlich Redaktion

<Impressum>

**Comment by KonstantinKo** [comment]
Das ist wahrscheinlich kein Bug, liegt nur an den unrealistischen Testdaten.

Die Email geht an den Initiator. BCC an alle Redakteure (`AdminUser.pluck(:email)`). Da stefanie.kaste sowohl Initiator-Email und Redakteur-Email ist, bekommt sie's halt doppelt.

**Comment by annakress** [comment]
Also ich als Initiator des Versprechens bekomme die Rückfrage eines anderen Nutzers auf jeden Fall doppelt zugestellt.

**Comment by annakress** [comment]
Kein Bug: als Initiator bekomme ich die Rückfrage nur einmal.

Aber noch mal anzuschauen:  Die Redaktion bekommt eine Kraut und Rüben Email. Außerdem wird Stefanies Email Adresse aus irgendeinem Grund als Undelivered Mail Returned to Sender versandt.

**Comment by annakress** [comment]
hat sich anscheinend erledigt.
