### ISSUE TITLE
Sämtliche auch nicht-veröffentlichte Pledges in Quelltext Suche verfügbar

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#159]
Wenn ich mit einem leeren String suche, https://beta.buntundverbindlich.de/de/pledges?query=

dann sehe ich die Pledges kurz aufflimmern, auch alle, die nur Entwurf Status haben. und sie sind im Quelltext der Seite einsehbar.

**Comment by KonstantinKo** [comment]
Kann den Fehler nicht reproduzieren.

Es kann gut sein, dass du zu dem Zeitpunkt umher geklickt hast und somit noch bestehende Daten im Speicher waren. wenn du die Seite einmal komplett neulädst sollten keine Entwürfe mehr im Quelltext stehen. Wir schmeißen aber für die Performanz keine Daten weg. Das heißt wenn du vorher auf deinem Profil warst und somit auch schon Pledge-Daten von Entwürfen im Memory hast, dann bleiben die auch dort. Du hast deswegen trotzdem nur Zugriff auf Daten, den du woanders auch hättest.

**Comment by annakress** [comment]
ok, kann das auf production auch nicht mehr nachvollziehen.
