### ISSUE TITLE
Flash Message styling

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#161]

**Comment by annakress** [comment]
Ist das dieses hier? Marc kann sich sicher etwas schönes überlegen.

![message](https://cloud.githubusercontent.com/assets/2988567/18054374/db7a7b98-6e03-11e6-96d3-97b1bf25a91f.png)

**Comment by marcaltmann** [comment]
Ist noch nicht ganz fertig und noch nicht gemerged, aber auf 161-flash zu sehen.

**Comment by marcaltmann** [comment]
![flash-beispiel](https://cloud.githubusercontent.com/assets/2727647/18068326/11737924-6e41-11e6-9ec9-6576478aeb2f.png)
