### ISSUE TITLE
Formular Success-State

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#163]
Wenn Formulare, bei denen man nach Abschicken die Seite nicht wechselt, erfolgreich versandt wurden, sollte wohl etwas passieren. Vielleicht soll eine Flash-Message angezeigt werden, vielleicht erstetzt man das Formular durch einen großen grünen Haken, vielleicht lässt man Konfetti über den Bildschirm rieseln. Die Frage ist was passieren soll und dann muss das natürlich umgesetzt werden.

Betrifft: PledgeView Update, PledgeView Signatur, Profil-Editierung (was vergessen?)

**Comment by annakress** [comment]
Ich mach mal dieses zu, da 2 der 3 Punkte schon gelöst sind.
