### ISSUE TITLE
Suche: Anzeige von non-results

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#164]
Siehe ruby test failure in `integration/search_test.rb`

Die Suche funktioniert soweit ich es sehen kann wie sie soll und gibt eine Variable `resultIds` zurück, die aber in der Anzeige-Logik in react nicht verwendet wird. Bedenke, dass  die `state.pledges` alle möglichen pledges beinhalten können, nicht nur diejenigen, die die Suche zurückgegeben hat

Möglicher Zusammenhang mit #159

**Comment by marcaltmann** [comment]
Test läuft.

**Comment by KonstantinKo** [comment]
Top
