### ISSUE TITLE
Neuigkeiten-Feld verschwindet nach Abschicken

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#167]
Wenn ich als Initiator eine Neuigkeit abschicke, verschwindet das Neuigkeiten Feld, und ich weiss nicht, was nun los ist, da ich keinerlei Rückmeldung bekomme.

Lösungsvorschlag:
Wir könnteneinen Bestätigungstext einblenden, so wie wir das auch bei Unterschriften machen: "Ihre Neuigkeit wurde veröffentlicht."

**Comment by marcaltmann** [comment]
Hmm, jetzt haben wir gleich zwei Benachrichtigungen. Einmal anstelle des Neuigkeiten-Formulars und ein weiteres Mal als Flash-Message.

**Comment by annakress** [comment]
ist gut so, danke!
