### ISSUE TITLE
Teilen über FB ist noch sehr rudimentär

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#169]
Sieht so aus, siehe Bild.

Im besten Fall teilen wir soetwas wie die Versprechenskachel.

![fb](https://cloud.githubusercontent.com/assets/2988567/18052100/befaf994-6df8-11e6-8042-46357112069c.png)

**Comment by marcaltmann** [comment]
Ich baue das bis morgen ein, aber es ist schwierig das zu testen, da Facebook nicht an unserem HTTP Basic Auth vorbeikommt, wenn es versucht, die Seite zu crawlen. Deshalb sieht es vermutlich auch so aus wie dort oben.

**Comment by marcaltmann** [comment]
Die Versprechensseiten haben jetzt für Facebook Open-Graph-Meta-Tags im <head>-Element.
181-opengraph

**Comment by annakress** [comment]
ok

**Comment by KonstantinKo** [comment]
Ist jetzt deployed, aber ich glaube es hat sich eigentlich nichts verändert, oder? Bitte nochmal draufschauen

**Comment by KonstantinKo** [comment]
Achso, in #181 steht was dazu… gut, dann machen wir's zu
