### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#172]
Zumindet bis zum tatsächlichen Launch sollten wir ein favicon für unsere Seite einbauen. Aus unserem eckigen Ubuntu-Logo lässt sich das ja auch ganz gut anstellen

**Comment by annakress** [comment]
Ich suchs mal raus.

**Comment by annakress** [comment]
Ich habe mal selbst ein transparentes favicon erzeugt, müsste man schauen, ob die Konvertierung nach .ico sinnvoll geklappt hat. Ist hier abgelegt: https://3.basecamp.com/3302998/buckets/570303/uploads/213669430

Leider schaffe ich es nicht, es in den Header zu integrieren. Es sieht für mich so aus, als würden wir den app/assets Ordner gar nicht nutzen, und ich verstehe nicht, wie ich das machen soll. also gerne übernehmen.

**Comment by marcaltmann** [comment]
Ich habs hinzugefügt, und zwar habe ich es einfach in den public-Ordner gelegt. Der assets-Ordner wird tatsächlich nicht wirklich genutzt, da wir die ganzen Assets über Webpack im Client-Ordner managen und dann beim build in den Rails-Assets-Ordner kopieren.

**Comment by marcaltmann** [comment]
Problem: Bei mir scheint das Favicon nicht mit Firefox zu funktionieren.

**Comment by annakress** [comment]
Bei mir gehts in Firefox. Wenn es in manchen Versionen nicht funktioniert, Pech, wir haben wichtigeres zu tun :-)
