### ISSUE TITLE
Persönliche Daten ändern / Bestätigung

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#174]
Wenn ich in meinem Profil meine Daten ändere, ob Name oder Bild etc. und auf den "Aktualisieren" Button klicke, bekomme ich keine Rückmeldung, ob die Aktualisierung geklappt hat. 

Es sollte eine Bestätigungsmeldung eingeblendet werden, und am besten auch auf den Kacheln, die ich ja auch im Profil sehe, gleich die neuen Daten angezeigt werden, sonst denke ich als Nutzer, dass das Aktualisieren nicht geklappt hat.

**Comment by KonstantinKo** [comment]
Duplikat zu #163

**Comment by marcaltmann** [comment]
Jetzt wird eine Nachricht angezeigt, dass die Daten aktualisiert wurden.

Die Kacheln enthalten auch die neuen Daten bis auf wenn sich das Bild aktualisiert. Die Bild-URL ist leider im Moment immer dieselbe, daher bekommt er die Änderung nicht mit.

**Comment by marcaltmann** [comment]
Bild wird jetzt auch aktualisiert.

**Comment by annakress** [comment]
Es funktoniert jetzt, danke!

Hab mich aber gewundert, weil wir sonst die Erfolgsmeldungen ja seit neuestem mit diesem Overlay einblenden, und hier wird ein Text über dem Button angezeigt. Können wir hier aus Konsistenzgründen auch das Overlay haben?

**Comment by marcaltmann** [comment]
Interessant. Ich probier mal das für Ajax-Sachen einzubauen.

**Comment by marcaltmann** [comment]
Sollte jetzt klappen.
