### ISSUE TITLE
Bild-Upload-Ausschnitt soll implizit übernommen werden

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#177]
Auch wenn man nicht auf den Zuschneiden-Button klickt.

**Comment by KonstantinKo** [comment]
Mit Validierung umsetzen

**Comment by annakress** [comment]
ich komm leider nicht dazu, erst irgendwann spätnachmittags vielleicht...könnt ihr bitte durchtesten? wäre super, das schon heute für etwaige bug-reports online zu haben.

**Comment by annakress** [comment]
ah, es wurde mit validierungs-fehlermeldung umgesetzt. ist für mich auch prima, muss nicht implizite übernahme sein.
