### ISSUE TITLE
Redakteur: Unterschriften sperren

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#178]
UAT-Dokument:
Unterschriften mit Kommentaren sperren
Als Portal-Redakteur kann ich über ein Admin-Backend einzelne Unterschriften mit Kommentaren zu Versprechen sperren, falls diese missbraucht werden.

**Comment by annakress** [comment]
Darf auch einfach Löschen sein, statt Sperren.

**Comment by annakress** [comment]
Ist schon gebaut mit dem Löschen.
