### ISSUE TITLE
Redakteur: Rückfragen sperren

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#179]
UAT-Dokument:
Rückfragen/Antworten sperren
Als Portal-Redakteur kann ich über ein Admin-Backend einzelne Fragen und Antworten zu Versprechen sperren, falls diese missbraucht werden.

**Comment by annakress** [comment]
Darf auch einfach Löschen sein, statt Sperren. Ist eventuell auch schon möglich?

**Comment by annakress** [comment]
Ja,ist schon gebaut, von mir.
