### ISSUE TITLE
Pledge-Titel in Suche einbeziehen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#180]
Ich habs versucht einzubauen, hat aber nicht geklappt.

**Comment by KonstantinKo** [comment]
Hast wahrscheinlich einfach `rake pg_search:multisearch:rebuild[Pledge]` nicht gekannt. Muss nach deploy auch auf production ausgeführt werden.

**Comment by marcaltmann** [comment]
Ja, außerdem schlugen allerdings drei ruby-Tests fehl.

**Comment by marcaltmann** [comment]
Funktioniert jetzt auch auf Production.
