### ISSUE TITLE
Versprechen über Social Media teilen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#181]
Versprechen über Social Media teilen
Als Webseitenbesucher kann ich interessante Versprechen einfach über Soziale Medien teilen. Wenn technisch möglich, in Form der Projekt-Kachel (siehe Wireframes). Björn hatte zudem angefragt, ob Einbindung von Whatsapp möglich ist.

Anna sollte das erwartete Verhalten für jeden Kanal festlegen.

related to #169

**Comment by marcaltmann** [comment]
https://developers.facebook.com/docs/sharing/webmasters

**Comment by marcaltmann** [comment]
Twitter und Facebook sollten jetzt gut funktionieren, kann das Ticket dann geschlossen werden?

**Comment by annakress** [comment]
ich sehe bei FB immer noch keine Änderung, aber hattest Du glaube ich erwähnt, dass es mit dem Passwort zu tun hat. Bei Twitter wird jedenfalls der richtige Link gepostet. Also gerne schließen.
