### ISSUE TITLE
Passwort vergessen Link kaputt

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#184]
Wenn ich in dem Menü Login auf Production au f den Passwort vergessen Link klicke, passiert nix.

**Comment by marcaltmann** [comment]
Müsste gefixed sein, bitte aber offen lassen, es gibt noch andere Pfade, die ich umstellen möchte.

**Comment by marcaltmann** [comment]
Fertig

**Comment by annakress** [comment]
Ja, jetzt gehts. Kannst gerne das Ticket schließen, wenn alle anderen Pfade fertig sind.
