### ISSUE TITLE
Responsive header / Menü fertigstellen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#189]

**Comment by marcaltmann** [comment]
@annakress Ich sitze ja gerade am Header: Wollen wir mal probieren, die Apostrophe rauszulassen aus den Links, also einfach "Ich versprechs" und "So funktionierts" schreiben? Ich finde sie nerven ein bisschen und sind nicht notwendig.

**Comment by annakress** [comment]
Ist aber leider grammatikalisch nicht korrekt.

**Comment by marcaltmann** [comment]
Sind wir denn an die amtliche Rechtschreibung gebunden? Ich habs mal als Empfehlung in einem Sprachblog (http://www.belleslettres.eu/) gelesen. FAZ usw. schreiben doch auch wie sie wollen.

**Comment by marcaltmann** [comment]
Ich hab jetzt die erste Version des responsive Headers fertiggestellt. Inkl. Sliding menu. Bitte einmal draufschauen.
Ich finde vor allem das Logo zu groß, würde evtl. den Text im Logo komplett weglassen.

**Comment by annakress** [comment]
Na ja, was heißt amtlich. Und ganz so willkürlich ist die FAZ auch nicht. Ich versprech`s ist natürlich auch  umgangssprachlich, aber zusammengeschrieben wird es einfach nicht. Wobei ich vermute, dass S. am Ende die Beschriftungen umschmeissen wird ;-)

**Comment by annakress** [comment]
Ich bin mit dem Menü zufrieden, vielen Dank! Nur statt Press sollte Presse stehen.

Das Logo würde ich erstmal so groß mit Untertitel belassen. Wir sind ja eine Plattform, die bisher keiner kennt. Für diese Phase ist ein auffälliges Branding, mit klarem beschreibendem Untertitel gar nicht so schlecht.
