### ISSUE TITLE
Frontend-Validierung wann?

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#192]
Im Moment arbeitet die Frontend-Validierung sofort nachdem man ein Feld verlässt. Ich finde das ein bisschen komisch. Vor allem wenn es mehrere Formulare auf der Seite gibt und ich ein bisschen herumklicke, werden mir gleich Fehlermeldungen angezeigt, obwohl ich kein Formular abschicken wollte.
Ich würde die Validierung lieber so einstellen, dass sie nach einem Sende-Versuch, also Button-Klick, anspringt. Was meint ihr?

**Comment by KonstantinKo** [comment]
Bei Button-Klick passiert es auch. Zeitpunkt-Optionen kann ich natürlich noch einbauen. Bedenke dass ein verschwindender Fehler onBlur aber auch ein gutes Nutzerfeedback ist. Wahlloses herumklicken auf Formulare die man nicht ausfüllen möchte ist im Zweifelsfall zwar für uns normales Verhalten, aber nicht für normale Seitenbesucher.

**Comment by annakress** [comment]
Hmm, ich kann mich da nicht wirklich entscheiden, da ich beides gut fnde. lasst uns gerne deshalb so lassen, und ich hole mir mehr feedback von nutzern ein.
