### ISSUE TITLE
Bug Date Picker

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#193]
Wenn ich im Versprechensformular das Ablaufdatum auswähle, und auf den heutigen Tag klicke (z.B. 05.09.) erscheint ausgewählt der 04.09.

Getestet Auf dem Production Server
Browser: Chrome auf Ubuntu

Hat eventuell mit der Diskussion in #36  zu tun? Stand der Diskussion war: wenn ich den 05.09. auswähle, dann läuft der Pledge noch bis 05.09. 23:59 Uhr., also bis Ende des ausgewählten Tages. Vermutlich damit zusammenhängend: Auf der Kachel sollte dann auch erst am 05.09. "0 Tage" angezeigt werden.

**Comment by marcaltmann** [comment]
Nein, hat nichts mit #36 zu tun, denke ich.
Ist gefixed, außerdem hab ich das maximale Datum für den Datepicker auf 3 Jahre vom jeweiligen Datum eingestellt.
