### ISSUE TITLE
Anrede bei Bestätigunsemail mit E-Mail-Adresse

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#199]
In meiner Bestätigungsmail wurde ich mit der E-Mail-Adresse angesprochen. Ist das so gewollt?

"Liebe/r mail@marcaltmann.com"

**Comment by annakress** [comment]
Ja, hatte ich gebaut, weil ich nicht an den Namen gekommen bin :-(

Ich stell es mal ins Backlog, Name ist natürlich besser.
