### ISSUE TITLE
3.3 Unterzeichner: Verpflichtung

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#20]
> Als Unterzeichner wird mir angezeigt, wozu ich mich verpflichte. Diese Verpflichtung muss ich als Opt-In ankreuzen und erhalte den Text als Mail zugeschickt.

**Comment by KonstantinKo** [comment]
Text als Mail muss noch eingetragen werden.

**Comment by annakress** [comment]
wartet auf björns input.

**Comment by annakress** [comment]
Text, sollte in die Email:

"Versprochen ist versprochen und wird nicht gebrochen“. Getreu diesem
Motto verstehen wir das „verbindlich“ bei „bunt und verbindlich“. Auf
dieser Plattform werden keine Verträge geschlossen. Wir vertrauen auf
unsere Nutzercommunity, dass ein Versprechen eingehalten wird. Es sollte
daher jedem Nutzer bewusst sein, dass ein Einstellen von Versprechen oder
auch das Unterzeichnen einen verbindlichen Charakter hat und wir
Spaßunterzeichnungen oder Versprechen die nicht ernst gemeint sind
kritisch sehen und im Wiederholungsfall auch sanktionieren. Lasst uns
daher gemeinsam tolle Versprechen umsetzen, die für alle Nutzer der
Plattform vor allem bunt aber auch verbindlich sind.
