### ISSUE TITLE
Neuigkeiten-Benachrichtigung falsch verschickt.

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#201]
Nachdem Anna eine Neuigkeit zu einem Versprechen gepostet hat, habe ich folgende Mail erhalten, obwohl ich das Versprechen nicht unterzeichnet habe (das Versprechen hatte keine Unterzeichner).

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Liebe/r Herr/Frau =

Zu dem von Ihnen unterzeichneten Versprechen wurde soeben eine Neuigkeit =
ver=C3=B6ffentlicht:
http://beta.buntundverbindlich.de/de/pledges/63

Falls Sie R=C3=BCckfragen zu der Neuigkeit haben, wenden Sie sich bitte d=
irekt an den Initiator. Nutzen Sie dazu den Bereich "Fragen an den Initia=
tor".

Mit besten Gr=C3=BC=C3=9Fen,
Ihre bunt und verbindlich Redaktion

<Impressum>

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Liebe/r Herr/Frau =

Zu dem von Ihnen unterzeichneten Versprechen wurde soeben eine Neuigkeit =
ver=C3=B6ffentlicht:
http://beta.buntundverbindlich.de/de/pledges/63

Falls Sie R=C3=BCckfragen zu der Neuigkeit haben, wenden Sie sich bitte d=
irekt an den Initiator. Nutzen Sie dazu den Bereich "Fragen an den Initia=
tor".

Mit besten Gr=C3=BC=C3=9Fen,
Ihre bunt und verbindlich Redaktion

<Impressum>

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Liebe/r Herr/Frau =

Zu dem von Ihnen unterzeichneten Versprechen wurde soeben eine Neuigkeit =
ver=C3=B6ffentlicht:
http://beta.buntundverbindlich.de/de/pledges/63

Falls Sie R=C3=BCckfragen zu der Neuigkeit haben, wenden Sie sich bitte d=
irekt an den Initiator. Nutzen Sie dazu den Bereich "Fragen an den Initia=
tor".

Mit besten Gr=C3=BC=C3=9Fen,
Ihre bunt und verbindlich Redaktion

<Impressum>

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Liebe/r Herr/Frau =

Zu dem von Ihnen unterzeichneten Versprechen wurde soeben eine Neuigkeit =
ver=C3=B6ffentlicht:
http://beta.buntundverbindlich.de/de/pledges/63

Falls Sie R=C3=BCckfragen zu der Neuigkeit haben, wenden Sie sich bitte d=
irekt an den Initiator. Nutzen Sie dazu den Bereich "Fragen an den Initia=
tor".

Mit besten Gr=C3=BC=C3=9Fen,
Ihre bunt und verbindlich Redaktion

<Impressum>

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf=
-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <p>Liebe/r Herr/Frau </p><p>Zu dem von Ihnen unterzeichneten Versprec=
hen wurde soeben eine Neuigkeit ver=C3=B6ffentlicht:<br /><a href=3D"http=
://beta.buntundverbindlich.de/de/pledges/63">http://beta.buntundverbindli=
ch.de/de/pledges/63</a></p><p>Falls Sie R=C3=BCckfragen zu der Neuigkeit =
haben, wenden Sie sich bitte direkt an den Initiator. Nutzen Sie dazu den=
 Bereich &quot;Fragen an den Initiator&quot;.</p><p>Mit besten Gr=C3=BC=C3=
=9Fen,<br />Ihre bunt und verbindlich Redaktion</p><p>&lt;Impressum&gt;</=
p>
  </body>
</html>

----==_mimepart_57d090ce4ec47_32903ff97f223fcc4212--

**Comment by annakress** [comment]
Ah, ich weiss warum. Du hast Deine Adresse als Admin eingetragen. Diese (kaputte) Mail geht im BCC an alle Admins. Also kein Bug, die kaputte Mail habe ich irgendwo als Issue, glaube ich.
