### ISSUE TITLE
Sticky Footer einbauen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#207]

**Comment by annakress** [comment]
Also ich sehe keinen Unterschied beim Footer. Mir ist nur aufgefallen, dass er fürs Smartphone nicht so schön ist.

**Comment by marcaltmann** [comment]
Ja, finde ich auch. Könnte man auch zweizeilig machen.

Der Sticky footer heißt, dass der Footer immer ganz unten ist, auch wenn die Seite fast leer ist, also dass die Seite mindestens so hoch ist wie das Browserfenster.

**Comment by annakress** [comment]
Ah, ok, das ist gut.
