### ISSUE TITLE
Auf Startseite werden teilweise zu viele Pledges angezeigt

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#212]
Wenn ich nach abgelaufenen, empfohlenen Pledges suche und dann auf die Startseite zurückkehre, werden im "Empfohlen"-Bereich auch die abgelaufenen angezeigt, weil sie noch im State sind. Herausfiltern.

**Comment by annakress** [comment]
Da würde ich aber nochmal bei Stefanie nachfragen, was erwünscht ist. Unter Umständen wollen sie ja auch abgelaufene als Best Practice Beispiele dort haben. Sie können sie ja selbst rausnehmen im Backend, wenn es nicth mehr passt.
