### ISSUE TITLE
4.1 Projektdurchführende: Berichte

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#22]
> Als projektdurchführender Initiator kann ich Berichte zu dem Projektstatus posten. Dazu wird die Neuigkeiten-Funktion wiederverwendet. Das System erinnert automatisiert daran, einen Abschlussbericht zu veröffentlichen. Die erste Erinnerung kommt direkt mit der Bekanntgabe, dass das Versprechen erfolgreich ist. Eine zweite Erinnerung kommt zwei Wochen später.  Bitte auch in cc an die Redaktion. Wird ein Abschlussbericht rechtzeitig gepostet, sollte die zweite Erinnerung entfallen.

Erwartetes Verhalten: 
* Neuigkeiten-Funktion ist nach Projektstart prominent oben rechts platziert.
* Initiator erhält die beschriebenen Erinnerungen per Email.

Anm. Anna: Das versenden einer zweiten Benachrichtigung bzw. das Entfallen von dieser: Dieser Fall kann auf Prio 3 gesetzt werden.

**Comment by KonstantinKo** [comment]
Braucht Email-Texte: `InitiatorMailer#needs_successful_update`

**Comment by annakress** [comment]
texte ergänzt, aber ich weiss nicht, wie ich das testen soll.
