### ISSUE TITLE
Polyfill für fetch einbauen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#223]

**Comment by annakress** [comment]
hier weiss ich nicht, was ich testen soll. falls konstantin testen soll, bitte ihn zuweisen.

**Comment by marcaltmann** [comment]
Ich teste es mal selbst.

**Comment by marcaltmann** [comment]
Oder bist du gerade bei den Browser-Tests, @annakress ? Es müsste getestet werden, ob man unter IE11 ein Formular abschicken kann.

**Comment by marcaltmann** [comment]
Neueste Version ist deployed.

**Comment by annakress** [comment]
ich mache das heute oder morgen, wollte zuerst tatsächlich den IE 10 testen. Oder hatten wir IE11 als Minimum?

**Comment by marcaltmann** [comment]
Irgendwann hast du glaub ich mal gesagt IE11 ist auch okay als Minimum, aber offiziell wars IE10.

**Comment by annakress** [comment]
Hat Bug #239 damit zu tun?
Alles andere hat in IE11 wie erwartet funktioniert.

**Comment by annakress** [comment]
Ich habe nochmal in die Emails geschaut, das Ministerium verwendet ja IE11. Also IE10 können wir mal ignorieren.

**Comment by marcaltmann** [comment]
Okay, ja, #239 liegt vermutlich daran dass der Polyfill noch nciht funktioniert.

**Comment by marcaltmann** [comment]
Polyfill funktioniert, der "Mehr Suchergebnisse" Button funktioniert in IE11. #239 muss daher eine andere Ursache haben.
