### ISSUE TITLE
Webpack Build-Prozess für Production verbessern

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#224]
- z.B. Digests über Webpack, nicht über Sprockets, wenn möglich.

**Comment by marcaltmann** [comment]
- Keine console.logs mehr auf Production
- JavaScript wird auf Production uglified/minified
- Open Sans Fonts nicht mehr über Google, sondern von uns

224-webpack

**Comment by annakress** [comment]
das sollte wohl konstantin testen? dann bitte ihn assignen.
