### ISSUE TITLE
Button zum Freischalten lassen von Versprechen auf Profilseite

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#225]
Stefanie hat gerade noch gesagt, dass sie den Button zum Freischalten lassen von Versprechen nicht gefunden hat und ihn gerne direkt auf der Profilseite hätte.

Was meinst Du Marc, kriegen wir überhaupt neben Bearbeiten + Löschen einen dritten Button unter den Kacheln untergebracht? Wenn die Schrift kleiner wird? Beschriftung wäre "Abschicken". Was kürzeres fällt mir nicht ein.

Nach Rücksprache mit Björn kann der Button direkt abschicken. Ich hatte gedacht, man müsste noch den Hinweis auf AGB/Datenschutz einbauen (wie in Vorschau), aber Björn meinte, ist nicht nötig.

**Comment by annakress** [comment]
danke, schaue ich mir in ruhe an und mache einzeltickets daraus.

**Comment by KonstantinKo** [comment]
Dabei ist zu beachten, dass das Versprechen zum Zeitpunkt des Entwurfs noch gar nicht komplett sein muss. Heißt, der Klick auf den Button kann auch fehlschlagen.

**Comment by marcaltmann** [comment]
@KonstantinKo Eigentlich schon, oder? Bei "Entwurf speichern" schlägt die Validierung doch auch an. Das einzige, was meiner Meinung nach passieren kann, ist, dass das ursprünglich ausgewählte Datum nicht mehr valide ist.
