### ISSUE TITLE
Versprechen gelöscht Email

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#226]
Wenn aktive Versprechen gelöscht werden, sollten die Unterzeichner per Email benachrichtigt werden.

**Comment by KonstantinKo** [comment]
@annakress Ist auf branch `226-pledge-deleted-email` vorbereitet. Bitte noch Emailtexte einfügen.

**Comment by annakress** [comment]
Ich habe es gerade lokal für die englische Übersetzung getestet, und es werden keine Emails verschickt, weder deutsch noch englisch. Oder die lokalen Testemails werden nicht gestartet (die werden ja im Browser angezeigt beim lokalen Test). Bitte noch einmal überprüfen. Auf Production habe ich noch nicht getestet.

**Comment by marcaltmann** [comment]
Bei mir funktionierts, allerdings werden E-Mails seit einiger Zeit auch nicht mehr automatisch geöffnet. Vielleicht ein Problem mit letteropener.
