### ISSUE TITLE
So funktioniert`s Text

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#231]
Hallo Marc,

der Text für /de/howitworks ist noch in der Review, aber so gut wie fertig. Ich kann den selber setzen (sind Paragraphen und Listen). Wie mach ich das am besten? Mit Paragraphen und Listenformattierung direkt auf Localeapp wie bei der FAQ? 

Danke, Anna

**Comment by marcaltmann** [comment]
Am einfachsten direkt im View als HTML/Slim, stylen müsste ich ihn danach noch.

**Comment by marcaltmann** [comment]
Ich hab den Text jetzt mal gesetzt.
Ohne Markdown, stattdessen direkt mit HTML. Wenn die Bezeichner für Übersetzungen mit "_html" enden, lässt sich darin direkt HTML verwenden.

**Comment by annakress** [comment]
sehr schön, danke, dann weiss ich für die nächsten texte bescheid.
