### ISSUE TITLE
Zeit übrig Anzeige falsch

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#233]
An diesem Versprechen (siehe Production), Screenshot vom 14.09. ist entweder die Zeitanzeige oder das Datum falsch:

![zeit](https://cloud.githubusercontent.com/assets/2988567/18508512/a1c63c5c-7a74-11e6-9d3e-a4ad44cfbb49.png)

Müsste doch 1 Tag sein, oder? Und dann 0 Tage, sobald wir den 15.09. haben. Wenn man es schick machen wollte, könnte man am letzten Tag dann auch die Stunden runterzählen, anstatt Tage :-)

**Comment by marcaltmann** [comment]
Ja, dachte auch schon mal daran, die Zeit runterzuzählen. Dann brauchen wir aber auf jeden Fall die Serverzeit, würde ich sagen.

**Comment by annakress** [comment]
Also die Stunden, das würde ich eher auf Prio 3 setzen. Wichtig wäre erstmal, die Tage zu korrigieren.

**Comment by annakress** [comment]
teste ich dann gerne direkt auf production.
