### ISSUE TITLE
Image-Upload-Button verbessern

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#237]
Ersetzen durch React-Dropzone

**Comment by annakress** [comment]
Der Ausschnitt-wählen Button im IE11 funktioniert nicht.

**Comment by marcaltmann** [comment]
@annakress Kannst du bitte wieder die Fehlermeldung posten?

**Comment by annakress** [comment]
IndexSizeError in

"use strict";function invokeGuardedCallback(name,func,a,b){try{return func(a,b)}catch(x){return void(null===caughtError&&(caughtError=x))}}var caughtError=null,ReactErrorUtils={invokeGuardedCallback:invokeGuardedCallback,invokeGuardedCallbackWithCatch:invokeGuardedCallback,rethrowCaughtError:function(){if(caughtError){var error=caughtError;throw caughtError=null,error}}};module.exports=ReactErrorUtils},function(module,exports,__webpack_require__){/**
	 * Copyright 2014-2015, Facebook, Inc.

**Comment by marcaltmann** [comment]
Fixed

**Comment by annakress** [comment]
kannst du gerne deployen, dann kann ich live reviewen.

**Comment by marcaltmann** [comment]
Ist es schon.
