### ISSUE TITLE
IE 11 Bug: Buttons funktionieren nicht

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#239]
Buttons funktionieren nicht. Ich konnte weder unterzeichnen noch eine Rückfrage absenden. Auch der Button "zur Vorschau" auf dem Versprechensformular funktioniert nicht.

**Comment by marcaltmann** [comment]
Problem liegt nicht am fehlenden "fetch" von IE11. Ich habe testweise die superagent-Bibliothek verwendet. Formulare funktionieren trotzdem nicht.

**Comment by annakress** [comment]
Die Errormeldung bei mir ist: "Das Objekt unterstützt die Eigenschaft oder Methode "set" nicht" im Abschnitt:

"use strict";function invokeGuardedCallback(name,func,a,b){try{return func(a,b)}catch(x){return void(null===caughtError&&(caughtError=x))}}var caughtError=null,ReactErrorUtils={invokeGuardedCallback:invokeGuardedCallback,invokeGuardedCallbackWithCatch:invokeGuardedCallback,rethrowCaughtError:function(){if(caughtError){var error=caughtError;throw caughtError=null,error}}};module.exports=ReactErrorUtils},function(module,exports,__webpack_require__){/**
	 * Copyright 2014-2015, Facebook, Inc.
	 * All rights reserved.
	 *

**Comment by annakress** [comment]
Hilft das weiter, oder soll ich mehr aufzeichnen mit dem Debugger?

**Comment by marcaltmann** [comment]
Wenn du noch mehr hast, bitte schicke es mal, es könnte weiterhelfen.

**Comment by KonstantinKo** [comment]
Bei mir lokal klappt es jetzt im IE aber wenn ich das auf production push kommt noch der selbe Fehler. Mach ich da was falsch beim push? @marcaltmann kannst helfen?

**Comment by marcaltmann** [comment]
@KonstantinKo  Im npm-shrinkwrap.json war die Quelle immer noch auf "resolved": "https://registry.npmjs.org/rform/-/rform-0.2.5.tgz", weshalb er die neue Version nicht gezogen hat.

**Comment by marcaltmann** [comment]
Funktioniert bei mir auf Production.

**Comment by annakress** [comment]
bei mir auch, danke! :-)
