### ISSUE TITLE
5.2 Redakteur: Pledges Veröffentlichen & Sperren

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#24]
> Als Portal-Redakteur kann ich über ein Admin-Backend Versprechen veröffentlichen oder bereits veröffentlichte Versprechen wieder sperren, falls z.B. Missbrauch vorliegt. Gesperrte Versprechen erscheinen nirgendwo auf dem Portal.

**Comment by annakress** [comment]
Ich kann als Redakteur Versprechen veröffentlichen, aber nicht wieder sperren, weil es dafür keinen Button gibt. Das frei-editierbare Feld, in das man den Zusatnd eintragen kann, scheint sich nicth auszuwirken. Für den Redakteur müsste es auch eher ein Dropdown sein.

**Comment by KonstantinKo** [comment]
Kann nun auch vom active-Zustand auf `disapproved` gesetzt werden. Natürlich geht auch einfach Löschen.

**Comment by annakress** [comment]
Ist noch nicht so richtig gut gelöst, da ich dann wiederum nicht mehr in active wechseln kann. Wir bräuchten einen Ansatz, wo die Redaktion den state flexibel hin-und hersetzen kann.
