### ISSUE TITLE
Keine Fehlermeldung, wenn kein Nutzerbild ausgewählt wird

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#242]
Beim Absenden passiert einfach gar nichts, Meldung dass man ein Bild auswählen muss, wird nicht angezeigt.

**Comment by annakress** [comment]
Hmm, ein Bild ist doch optional?

**Comment by marcaltmann** [comment]
Komisch, das Formular ließ sich nicht absenden. Jetzt funktionierts.
