### ISSUE TITLE
5.3 Redakteur: Statistiken

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#25]
> Als Portal-Redakteur kann ich über ein Admin-Backend Statistiken zu dem Portal einsehen: 
- [ ] Anzahl abgeschickter Versprechen 
- [ ] Anzahl veröffentlichter Versprechen 
- [ ] Anzahl gesperrter Versprechen 
- [ ] Anzahl registrierter Nutzer, unterteilt nach Unternehmen, Organisationen und Privatpersonen
- [ ] Anzahl Unterschriften gesamt über alle Versprechen
- [ ] Sortierung aller veröffentlichten Versprechen nach Anzahl Unterschriften (also erfolgreichste Versprechen finden)
- [ ] Angabe der Suchkriterien die von Nutzern benutzt werden

**Comment by annakress** [comment]
alle erledigt, ausser  "Angabe der Suchkriterien die von Nutzern benutzt werden".
eventuell machen wir das über google analytics, lassen wir erstmal weg.
