### ISSUE TITLE
Bild-Upload-Komponente hat Layout-Bugs im IE11

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#251]
Bei großen Bildern wird die gesamte Komponente zu groß, reicht an den rechten Bildschirmrand.

**Comment by marcaltmann** [comment]
Hallo @annakress ,
bist du damit einverstanden, dass ich den Tooltipp an eine andere Stelle schiebe? Das würde den Layout-Bug beheben bzw. umgehen:
![tooltip](https://cloud.githubusercontent.com/assets/2727647/19145357/e83786b4-8bae-11e6-857c-53be942df59e.png)

**Comment by annakress** [comment]
ja
