### ISSUE TITLE
Selenium für Integration-Tests installieren

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#253]

**Comment by marcaltmann** [comment]
Selenium funktioniert offenbar nur mit Firefox <= 47.

**Comment by marcaltmann** [comment]
Im Zweifelsfall die Extended Support Release installieren, Firefox ESR 45. Hab ich auch gerade gemacht und funktioniert.

**Comment by annakress** [comment]
soll das jemand reviewen? also von mir aus kann erstmal geschlossen werden.
