### ISSUE TITLE
Video + Text auf Startseite

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#256]
Text siehe https://docs.google.com/document/d/1goJApMfjjW3rAJyk7h97dKmq5Pzva3uPx2COvF6rhlg/edit

Video an Marc verschickt.

Positionierung Video + Text siehe Startseitenentwurf von Tino.

**Comment by marcaltmann** [comment]
Im Google-Dokument gibt es keine Überschriften für den Startseiten-Text, in Tinos Entwurf gibt es zwei. Soll da noch eine Überschrift dazu?

**Comment by marcaltmann** [comment]
Zum Testen auf 256-startpage.

**Comment by annakress** [comment]
ich schicke demnächst den link zum richtigen video, weiss nicht, ob ich das morgen hinbekomme zeitlich. startseite kann aber gerne auch erst nächsten di online, ist ncith so dringend.

**Comment by annakress** [comment]
Da uns keine Überschriften gegeben wurden, würde ich die auch weglassen. Dann kann man den Text auch schöner mit der Höhe des Videos alignen. Ich probier gleich mal, das echte Video auf einen anderen Account hochzuladen.

**Comment by marcaltmann** [comment]
Kann begutachtet werden.

**Comment by annakress** [comment]
ich schick mal einen screenshot an stefanie, ob das so ok ist.

es ist etwas blöd, dass der video-player so aussieht, als wäre er nicht mit dem text aligned, aber wenn das video startet, ist er eigentlich richtig positioniert. keine ahnung, was man da machen könnte, einen grauen rahmen um den videoplayer? 

wir können sicher morgen von stefanie erfahren, ob das morgen so deployed werden soll.

![video](https://cloud.githubusercontent.com/assets/2988567/19046091/270c2e40-899c-11e6-989f-6015bea09e28.png)

**Comment by marcaltmann** [comment]
Das mit dem Rahmen sieht ok aus, finde ich:
![startpage](https://cloud.githubusercontent.com/assets/2727647/19047812/b4db032a-89a3-11e6-9463-84d3ac678a6a.png)

**Comment by annakress** [comment]
ja, lass uns gerne so machen.

und stefanie hat gerade einen tippfehler entdeckt: Im Text ist ein Fehler versteckt. Kannst du bitte bei „Wir wollen Ihr Engagement bündeln..:" das „zu" streichen? Das ist dort falsch.

**Comment by annakress** [comment]
freigabe für di-deployment steht aber noch aus.

**Comment by annakress** [comment]
björn meint, das video soll erst do/fr online.

**Comment by marcaltmann** [comment]
Okay, aber in dem Satz: „Wir wollen Ihr Engagement bündeln..:"
Ist das ein "Ihr" oder ein "ihr"? Im Text ist es klein.

**Comment by annakress** [comment]
stimmt, beides wäre möglich. aber lass uns das so lassen.
