### ISSUE TITLE
Korrekturen So funktionert`s

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#257]
Hallo Anna,

hier jetzt doch nochmal zwei Korrekturbitten zwischendurch. ;-)

1. Kannst du auf der Seite „So funktioniert`s" am Anfang eine Übersicht mit den Überschriften machen, die als Links funktionieren? Dann müssen die Nutzer nicht die ganze Seite scrollen, sondern können direkt zu dem Punkt springen, der für sie wichtig ist.

2. Kannst du außerdem zwischen den einzelnen Punkten unter „Wie funktioniert das Einstellen eines Versprechens" immer eine Leerzeile setzen? Das sieht sonst so gequetscht aus.

3. Außerdem wäre es schön, wenn unter der Überschrift „Wie kann man konkret helfen" die beiden Punkte „Durch das Einstellen eines Versprechens" und „Durch das Unterzeichnen eines Versprechen" fett markiert wären.

Danke dir und viele Grüße
Stef

**Comment by annakress** [comment]
2 + 3 erledigt.

1 steht noch aus.

**Comment by annakress** [comment]
würde ich 1 einfach als html auf localeapp setzen? @marcaltmann

**Comment by marcaltmann** [comment]
Im Prinzip ja, dabei würde ich mich an der FAQ orientieren, also die CSS-Komponente c-toc mit c-toc__list usw. verwenden. Am besten schaust du dir dafür an, wie die FAQ-Seite gerendert wird.

**Comment by annakress** [comment]
muss ich nicht testen, wird schon passen :-)
