### ISSUE TITLE
Korrektur FAQ Seite

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#258]
Könntest du hier auch ganz am Anfang so eine Übersicht der Überschriften machen, die dann als Links fungieren?

Das wäre super.

**Comment by KonstantinKo** [comment]
@marcaltmann Ist auf branch `258-faq-table-of-contents` vorbereitet. Bitte noch stylen

**Comment by marcaltmann** [comment]
Sieht jetzt so aus.
![toc](https://cloud.githubusercontent.com/assets/2727647/19047039/740c4334-89a0-11e6-8d0d-30c7a5d5b1a8.png)

**Comment by annakress** [comment]
fuktioniert, prima!
