### ISSUE TITLE
Error monitoring

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#269]
@KonstantinKo Kennst du evtl. eine gute Lösung um Exceptions auf Production zu sammeln? Sowas wie HoneyBadger oder so?

**Comment by marcaltmann** [comment]
Eventuell exception notification gem einbauen:
https://github.com/smartinez87/exception_notification

Dafür brauchen wir dann eine E-Mail-Adresse.

**Comment by annakress** [comment]
habt ihr eine wunschadresse? ich würde für uns support@buntundverbindlich.de aufsetzen.

**Comment by marcaltmann** [comment]
Klingt so, als könnten da auch Nutzer hinschreiben. Ich würde lieber eine eigene E-Mail-Adresse nur für die Exceptions nehmen, z.B. exception-notification@buntundverbindlich.de

Falls wir doch einen der 50$-Dienste nehmen sollten, brauchen wir das nicht.

**Comment by annakress** [comment]
exception-notification@buntundverbindlich.de angelegt mit weiterleitung auf uns drei.

**Comment by KonstantinKo** [comment]
@annakress Ich möchte diese Emails ungern auf meine Hauptadresse weitergeleitet haben. Ich denke es ist schon ok wenn man in das postfach manuell nachschauen kann oder es sich in seinem email-programm als separaten account einrichtet
