### ISSUE TITLE
Bilder lassen sich nicht löschen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#274]
Wenn ich im Versprechen oder im Profil ein Bild hinzufüge, kann ich es nicht mehr löschen (höchstens ersetzen). Man sollte es aber wieder löschen können.

**Comment by KonstantinKo** [comment]
@marcaltmann Auf branch 274-remove-image (basiert auf redux refactoring) gibt es jetzt eine funktionierende aber ungestylte checkbox unter der Bildkomponente, die bestehende Bilder löscht. (Commit 1d61450 ist aber cherry-pick-bar)

Was fehlt ist jetzt sicherlich entweder ein styling der Checkbox oder diese zum hidden-field machen was bei Klick von einer neuen Schaltfläche den Wert "1" bekommt.

**Comment by annakress** [comment]
stefanie meinte auch, dass sich bilder nicht ersetzen lassen (als normaler nutzer im versprechensformular, als admin klappt es, hab ich getestet), bitte auch kurz testen. das betreffende versprechen war noch im status  initiated (oder wie der erste status heisst...also noch nicht abgeschickt.)

**Comment by annakress** [comment]
klappt jetzt alles.
