### ISSUE TITLE
Bitte 2 Bilder löschen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#276]
Diese Versprechens-Bilder sollen laut Stefanie wieder gelöscht werden, kann man derzeit höchstens manuell:

https://beta.buntundverbindlich.de/de/pledges/105

https://beta.buntundverbindlich.de/de/pledges/104

**Comment by marcaltmann** [comment]
Sind jetzt erstmal gelöscht über die Rails-Konsole:
pledge=Pledge.find(104)
pledge.remove_image = true
pledge.save!

Aber ich habe bisher keine Möglichkeit gefunden, den CarrierWave-Uploader sauber zu löschen. Irgendwo ist der Bildpfad noch gespeichert.
Auch wäre es schön, wenn Stefanie überprüfen könnte, ob sich andere Bilder hochladen lassen bei Pledge 104/105.

**Comment by annakress** [comment]
danke! da die pledges schon aktiv sind, sind sie ja nur noch übers backend bearbeitbar. dafür habe ich code geschrieben, weil das bearbeiten übers backend auch nicht ging.

**Comment by marcaltmann** [comment]
Achso, ja, klar. Ich probiers nachher mal aus.
