### ISSUE TITLE
Keine Paragrafen im Info-Text möglich

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#277]
Wenn ich im Versprechensformular im optionalen Info-Feld einen Text schreibe, sind keine Paragraphen möglich, also

satz1

satz2

wird in der Vorschau zu: satz1 satz2

Auch Html mit <p> ist nicht möglich.

Also ich würde Html ungern einführen (kann nicht jeder), wenn es technisch möglich ist, Paragraphen durch Leerzeilen zu setzen.

**Comment by marcaltmann** [comment]
Newlines werden jetzt in <br/>-Tags übersetzt.

**Comment by annakress** [comment]
sieht gut aus, danke!
