### ISSUE TITLE
Redux-Reducer refaktorieren

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#287]

**Comment by annakress** [comment]
sieht alles gut aus (ich habe alle formulare durchgetestet), bis auf folgenden sonderfall:
 
ich habe als neuer bentuzer ein versprechen angelegt und freischalten lassen. ich poste eine neuigkeit, aber die seite zeigt mir kein feedback (keine meldung, dass neuigkeit abgeschickt, seite wird nicht neu geladen). wenn ich die seite manuell neu lade, erscheint die neuigkeit korrekt. Problem tritt nicht bei alten nutzern auf, dort gibt es feedback und die seite wird neu geladen. bitte noch einmal kurz testen.

**Comment by annakress** [comment]
ich habe jetzt keinen browser-test gemacht, gerade IE, das würde ich eher auf Live machen. wenn ich auf irgendwelche spezialfälle beim testen achten muss, bitte bscheid geben.

**Comment by marcaltmann** [comment]
Das eine ist ein Bug in einem Mailer, siehe #294.

Es gibt m.W. keine Änderungen, die Auswirkungen auf den IE haben sollten. Aber ich werde es heute oder morgen Vormittag auch nochmals schnell darauf testen.
