### ISSUE TITLE
Anzeigen "von der Redaktion empfohlen" falsch

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#291]
Auf Production ist die Anzeige der markierten Pledges nicht korrekt ist. 6 Pledges im Zustand active sind markiert, es werden aber nur 4 auf der Startseite angezeigt.

**Comment by marcaltmann** [comment]
Auf Branch 291-limit-pledges...

**Comment by annakress** [comment]
woran lag es nun? sonst weiss ich nicht genau, was ich testen soll. also von mir aus kannst du das deployen, wenn du das selbst getestet / nachvollzogen hast.

**Comment by annakress** [comment]
stefanie meldet, dass derzeit auf der startseite auch der bereich neueste versprechen nicht auf 12 beschränkt ist. es werden 13 angezeigt. ist das ein verwandtes problem oder ein neues ticket?

**Comment by marcaltmann** [comment]
Ist auch bereits gefixed.
