### ISSUE TITLE
Alle Versprechen lassen sich nicth anzeigen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#292]
Auf https://beta.buntundverbindlich.de/de/pledges geht der Button "Mehr anzeigen" wieder nicht. Das war doch schon mal behoben, oder?

**Comment by marcaltmann** [comment]
Das liegt daran, dass Pledge Nr. 99 keinen Initiator hat. Allerdings weiß ich leider nicht, wie es dazu gekommen ist.

**Comment by annakress** [comment]
oh, es kann sein, dass ich oder stefanie beim aufräumen für den beta-launch den initiator, aber nicht den pledge gelöscht haben. ich frag mal stefanie.

**Comment by marcaltmann** [comment]
Ja, schlage ein "dependent: :destroy" vor, @KonstantinKo .

Außerdem fallen mir dabei zwei Sachen auf:
- Ich habe den Fehler nur gefunden, weil wir Logging auf Production noch eingeschaltet haben. Ohne Logging, dass wir vermutlich ausschalten sollten, wäre es sehr schwierig geworden.
- Es wurden gar keine Pledges angezeigt, weil ein einziger Pledge fehlerhaft war. Das könnte auch besser sein, vermutlich indem wir richtiges Exception Handling auf JS-Seite einbauen.

**Comment by annakress** [comment]
stefanie hat das versprechen gelöscht, und der button funktioniert wieder. sie konnte nicht nachvollziehen, wohin der initiator verschwunden ist. ich geh aber mal vom löschen aus.

dependent destroy klingt sinnvoll, ich muss stefanie dann nur vorwarnen, damit sie beim löschen bescheid weiss.

logging - müsst ihr entscheiden, geht es um performanz, dass man es abschalten sollte?

**Comment by marcaltmann** [comment]
Logging ist eher ne Stilfrage, würde ich sagen.

**Comment by annakress** [comment]
Speichern wir da auch IP Adressen? Benötige die Info für die Datenschutzerklärung.

**Comment by KonstantinKo** [comment]
Ja, js logging sollten wir vor dem richtigen launch noch abstellen. Das ist aber kein klassisches logging wo dinge permanent auf dem server gespeichert werden. Die rails server logs speichern soweit ich weiß keine IPs, nein.

**Comment by annakress** [comment]
für mich zum verständnis: wenn es beim auffinden von fehlern hilfreich ist, warum stellt man das logging dann ab?

**Comment by KonstantinKo** [comment]
Weil wir damit Nutzern Informationen preisgeben, auf die sie sonst keinen direkten Zugriff haben, weil es uns das Server-Log sehr voll macht und weil es Performance-Einbußen mit sich bringt. Aus diesen Gründen ist es tatsächlich auch schlechter Stil.

**Comment by annakress** [comment]
danke, alles klar.

**Comment by annakress** [comment]
ist hier noch etwas zu reviewen? soll das in das nächste deployment unbedingt rein?

**Comment by marcaltmann** [comment]
Ob das Destroyen so funktioniert wie gewünscht könntest du testen. Ich glaube wir hatten gesagt, dass das nicht mehr mit deployed wird.

**Comment by annakress** [comment]
ja, lass uns das erstmal zurückstellen.
