### ISSUE TITLE
Update-Mailer funktioniert nicht, wenn es noch keine Unterzeichner gibt

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#294]
ich habe als neuer bentuzer ein versprechen angelegt und freischalten lassen. ich poste eine neuigkeit, aber die seite zeigt mir kein feedback (keine meldung, dass neuigkeit abgeschickt, seite wird nicht neu geladen). wenn ich die seite manuell neu lade, erscheint die neuigkeit korrekt. Problem tritt nicht bei alten nutzern auf, dort gibt es feedback und die seite wird neu geladen. bitte noch einmal kurz testen.

**Comment by marcaltmann** [comment]
Gefixed in 294-mailer-bug.

**Comment by annakress** [comment]
ich komme morgen vormittag vermutlich nicht zum testen, aber kann gerne deployed werden.
