### ISSUE TITLE
5.8 Redakteur: Bericht-Erinnerung

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#30]
> Als Portal-Redakteur kann ich über ein Admin-Backend alle erfolgreichen Versprechen listen, die in die Umsetzungsphase gestartet sind, und deren Berichtfrist abgelaufen ist, damit ich die Akteure daran erinnern kann, einen Bericht zu veröffentlichen. Um sie zu erinnern, kann ich eine Email an die Akteure verschicken.

**Comment by annakress** [comment]
machen wir erstmal zu.
