### ISSUE TITLE
Plattform erlaubt Upload sehr großer Bilder / Facebook

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#320]
Das Versprechensbild unter

https://www.buntundverbindlich.de/de/pledges/144

ist 10MB, was bei uns eigentlich ausgeschlossen ist. Vermutlich ohne JavaScript hochgeladen?

Facebook-Sharing-Bilder dürfen maximal 5MB groß sein, deshalb erscheint beim Teilen des Versprechens das Ministeriumslogo.

**Comment by marcaltmann** [comment]
Vielleicht wurde das Bild auch übers Backend eingestellt.

**Comment by annakress** [comment]
Die meisten Pledges bisher hat Stefanie erstellt, und dann die Email geändert, deshalb kann es gut sein, dass es übers Backend ging.

**Comment by marcaltmann** [comment]
Bestehende Bilder müssten neu zugewiesen werden, z.B. so:
p = Pledge.find(...)
p.image = File.open(p.image.file.path)
p.save

**Comment by annakress** [comment]
alle bilder, oder nur die großen?

**Comment by marcaltmann** [comment]
nur die großen
