### ISSUE TITLE
Improve Facebook sharing

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#322]
- Bildmaße bei Versprechensbild und User-Avatar im Model mitspeichern, siehe
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Get-image-dimensions
- Maße als OpenGraph-Tags angeben, damit Bild gleich beim Sharen angezeigt wird.
- Wenn es Nutzerbild mit 200x200 gibt, dann das anstelle des buv-Logos nehmen
- evtl. Tests für OpenGraph-Tags schreiben

**Comment by annakress** [comment]
ich bin mir nicht sicher, was sich nun geändert hat, kann auf production keine offensichtliche änderung sehen.

**Comment by marcaltmann** [comment]
Ist noch nicht ganz fertig, ich muss für die bestehenden Pledges und User die Bildmaße, die jetzt in den Models gespeichert werden, noch zuweisen.

**Comment by marcaltmann** [comment]
Es gibt auch noch einen Bug, durch den die Pfade für die Facebook-Bilder falsch angegeben werden.

**Comment by marcaltmann** [comment]
Der Bug ist auf develop behoben, sobald der Fix deployed ist, werde ich die Bildmaße auf Production nachtragen.
