### ISSUE TITLE
Alle Versprechen Sortierung

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#323]
Wenn ich auf alle Versprechen klicke - es ist unklar, wie sortiert wird, insbesondere wenn ich dann den Mehr anzeigen Button klicke, ändert sich die Sortierung. Ist verwirrend, und wir sollten uns etwas überlegen.

**Comment by marcaltmann** [comment]
Abgesehen von dem Bug ist die Sortierung etwas komisch: Im Moment wird einfach nach Deadline sortiert, absteigend, damit die gelungenen/gescheiterten Versprechen unten sind.
Das führt natürlich dazu dass man ganz oben die hat, die noch am meisten Zeit haben, was ja auch Quatsch ist. Vorschlag: Zumindest innerhalb der aktiven Versprechen nach Deadline aufsteigend sortieren.

**Comment by annakress** [comment]
für die sortierung hatte mir stefanie etwas vorgeschlagen, muss ich noch abstimmen.

**Comment by marcaltmann** [comment]
Alle Versprechen sortieren anhand von created_at, absteigend
