### ISSUE TITLE
Mehr Anzeigen in Alle Versprechen hängt manchmal

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#324]
Lässt sich nicht ganz klar reproduzieren, aber manchmal lädt der Button die Versprechen nicht nach (z.B. jetzt... und dann geht es wieder problemlos), es sieht jedenfalls merkwürdig aus. Eventuell wird ein Suchindex bei neuen Versprechen aufgebaut, und dann hängt die Seite noch ein wenig hinterher?

Ist jetzt nichts für den Launch, aber wir sollten uns das bald anschauen.

**Comment by marcaltmann** [comment]
@annakress Die Reihenfolge in der Versprechen zurückgegeben wurden war nicht ganz genau festgelegt, daher kam es beim Nachladen zu Fehlern.
Ich kann es noch deployen, wenn du magst.

**Comment by marcaltmann** [comment]
Pull Request #325

**Comment by annakress** [comment]
wenn es recht unkritisch ist, ok! danke!

**Comment by marcaltmann** [comment]
Ist online und sieht jetzt besser aus. Bitte nochmals kurz testen.
