### ISSUE TITLE
Startseite über FB teilen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#327]
Stefanie fragt nach, ob wir beim Teilen der Startseite noch nachbessern könnten. Die Auswahl der Bilder zum FB-Post ist nicht so toll.

Einfachste Lösung: Logo mit Claim nehmen.

Stefanie hat gefragt, ob man auch quasi ein Miniaturbild der Startseite teilen könnte, ist denn so etwas möglich, Marc? Nach meinem Wissen ja nur Bilder, die direkt auf der Seite vorkommen, oder kann man ein beliebiges Bild hinterlegen?

**Comment by marcaltmann** [comment]
Ja, man kann auch ein beliebiges Bild hinterlegen, aber das Seitenverhältnis sollte ungefähr 2:1 sein, also doppelt so breit wie hoch, das macht es etwas schwierig.

**Comment by marcaltmann** [comment]
Im Moment wird das Familienministeriums-Bild angezeigt. Stattdessen Logo anzeigen.
