### ISSUE TITLE
Verbesserung Fragen/Antworten Eingabe

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#333]
Bitte von Stefanie (für Antworten, aber dürfte für Fragen das Gleiche sein):

Kann man das Eingabefeld so einstellen, dass man irgendwie am Ende den gesamten Antworttext sieht und nochmal auf Fehler durchlesen kann? Momentan ist das nur eine ganz lange Spalte, was das Korrigieren anstrengend macht, da du den Text ewig vor und zurücklaufen lassen musst, um nochmal zu lesen.

Vorschlag Anna: Eine Input Area?

**Comment by marcaltmann** [comment]
Ja, können wir machen, ich sehe auch nichts, was dagegen spricht. Wir müssten nur entscheiden, ob wir Zeilenumbrüche dann ignorieren oder sie berücksichtigen, wie wir es ja in der Versprechensbeschreibung jetzt auch machen.

**Comment by annakress** [comment]
Da es eher ein Format für kurze Texte ist, schlage ich vor, Zeilenumbrüche zu ignorieren.

**Comment by annakress** [comment]
sieht gut aus, danke!
