### ISSUE TITLE
Email wenn jemand unterschreibt

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#336]
Wenn jemand ein Versprechen unterschreibt (also erst nachdem er die Unterschrift auch bestätigt hat), sollte der Initiator eine Email bekommen. Auch der Admin sollte eine Email im BCC bekommen.

**Comment by KonstantinKo** [comment]
Ist vorbereitet, braucht noch Email-Text.

**Comment by annakress** [comment]
hier bitte noch warten mit dem deployment. ich will stefanie erst fragen, ob das erst online gehen soll, wenn sie generell die emails abstellen kann.
