### ISSUE TITLE
iOS Safari Grafikbug: Kacheln mit 4-zeiligen Titeln

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#345]
Wurde mir von einem Freund geschickt, der die Seite mit seinem iPhone aufgemacht hat:
![image](https://cloud.githubusercontent.com/assets/779660/19685953/48c9699c-9abf-11e6-822f-679abdaea21d.png)

Zu finden auf der Homepage, passiert nur bei Kacheln mit 4-zeiligem Titel

**Comment by marcaltmann** [comment]
Duplikat von #331
