### ISSUE TITLE
Anpassung Mail-Layout

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#350]
Anbei die Vorlage von Melanie. Eine Vorlage ist es nicht wirklich, nur eine grobe Vorgabe. Es soll das Logo in alle Emails oben rein, und die Signatur von Stefanie mit Links in den Footer. Bei den Fonts würde ich vorschlagen, sich an die Webseite zu halten.

Marc, meinst Du, Du kannst daraus ohne weitere Vorgaben etwas schönes machen? Können wir in unsere HTML-Mails ohne weiteres CSS einbinden?

[Entwurf automatische Mail.pdf](https://github.com/initiatived21/d21/files/581476/Entwurf.automatische.Mail.pdf)

**Comment by marcaltmann** [comment]
Sollte kein Problem sein, auch das mit dem CSS, allerdings habe ich bisher noch keine HTML-E-Mails gemacht, ich muss mich da noch einlesen, auch was z.B. Bilder oder Fonts betrifft (mitschicken oder verlinken).

**Comment by marcaltmann** [comment]
@annakress Soll das Layout denn für alle Mails sein? Und das alte Impressum soll vermutlich ersetzt werden, oder?

**Comment by annakress** [comment]
Ja, für alle Emails. Hmm, wegen Impressum frag ich noch mal nach, kann sein,dass es vergessen wurde, ein rechtskonformes Impressum einzubauen...

**Comment by marcaltmann** [comment]
Hier ist mal ein Zwischenstand:

Wie in der Vorlage habe ich hier zwei Fonts benutzt, einen Serifenfont für den E-Mail-Text. Den haben wir allerdings nicht auf der Webseite, ist aber vielleicht besser lesbar.

![screenshot-mail](https://cloud.githubusercontent.com/assets/2727647/20183433/93c44a40-a765-11e6-842b-804c98147933.png)

**Comment by annakress** [comment]
ich habe den entwurf an melanie geschickt, mit der rückfrage zu einem rechtskonformen Impressum in der Email.

**Comment by marcaltmann** [comment]
Noch testen: einen der initiator-mailer o.ä.
