### ISSUE TITLE
Partner/Sponsoren auf "Über uns"

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#352]
Es soll ein weiterer Abschnitt zu Über Uns rein, nämlich "Partner".

Wir warten noch auf Logos und Links.

**Comment by annakress** [comment]
Auf der Über Uns Seite soll unten ein Abschnitt Partner und ein Abschnitt Sponsoren hinzugefügt werden.
Dort sind die Logos mit Links aufgelistet.

Partner soll zudem folgenden Text enthalten, unter dem die Logos kommen (Logos in einer Spalte, wenn möglich):

bunt und verbindlich möchte die Arbeit bestehender Flüchtlingsinitiativen unterstützen und dazu beitragen, das tolle Engagement dieser Initiativen zu stärken. Im Rahmen unseres Projekts haben wir diese Initiativen und ihre Arbeit kennengelernt. Sie alle tragen dazu bei, dass Geflüchtete Teil unserer Gesellschaft werden können. Dafür sagen wir DANKE!

TODO: Englische Übersetzung kommt bald.

**Comment by marcaltmann** [comment]
Hallo, hier mein Vorschlag. Nicht alle in einer Zeile, aber dass alle Logos gleich hoch sind, halte ich für die beste Art und Weise, eine Sponsorenliste zu machen, die ich kenne. Das "Go Volunteer"-Logo ist ein bisschen schlecht lesbar, vielleicht kann man hier auch eine nicht-quadratische Version machen?

Normale Version:
![sponsors](https://cloud.githubusercontent.com/assets/2727647/20353976/ebde6bc8-ac1c-11e6-9e3c-514dc952017b.png)

Mobile Version:
![sponsors-small](https://cloud.githubusercontent.com/assets/2727647/20353980/ee8ed42a-ac1c-11e6-8655-75e7ceb77622.png)

**Comment by annakress** [comment]
Danke, sieht schon mal schön aus. Wichtig wäre aber, dass alle Logos lesbar sind und visuell gleich gewichtet. GoVolunteers kann man gar nicht mehr lesen, leider. Start Coding dagegen wirkt riesig.

Logos anzupassen, ist so eine Sache, da muss man immer Rücksprache halten, und S. hat lange benötigt, bis die Organisationen was geschickt haben. Das Fass würde ich ungerne wieder aufmachen.

Könnten wir die Logos so skalieren, dass die Schriften ungefähr alle gleich groß sind und gleich gut lesbar? Ich verstehe, dass es etwas tricky ist. Was meinst Du?

**Comment by marcaltmann** [comment]
Okay, ich probier mal was.

**Comment by marcaltmann** [comment]
Hier die neue Version. Jetzt nehmen die Logos alle dieselbe Fläche ein.

![sponsors](https://cloud.githubusercontent.com/assets/2727647/20394037/7898a544-acde-11e6-9c4d-c921d89b006d.png)

Mobil:
![sponsors-mobile](https://cloud.githubusercontent.com/assets/2727647/20394042/7d5266e2-acde-11e6-9e33-5bc246a1476e.png)

**Comment by annakress** [comment]
sieht gut aus, können wir gerne so machen.
