### ISSUE TITLE
Flag, um Benachrichtigungen für bestimmte Initiatoren abzuschalten

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#354]
Da die Redaktion zur Zeit viele Pledges selbst für die Unternehmen pflegt, sollen ausgewählte Initiatoren gar keine automatisierten Emails bekommen.

Vorschlag: Im Backend kann ein Flag für ausgewählte Nutzer gesetzt werden. Ist der Flag gesetzt, bekommen sie gar keine automatisierten Emails. Die BCC-Email an die Redaktion soll aber trotzdem verschickt werden.

**Comment by KonstantinKo** [comment]
Eventuell über Email-Prefix lösbar [(schnell gefundener Link)](http://www.wikihow.com/Use-Plus-Addressing-in-Gmail)

**Comment by annakress** [comment]
Hab ich getestet und funktioniert prima mit Gmail. Habe gerade Stefanie gefragt, ob das eine gute Lösung wäre.

**Comment by KonstantinKo** [comment]
Das ist gut. Ansonsten müsste ich wirklich noch ein bisschen was umschreiben damit die Redaktion trotzdem emails bekommt.

**Comment by annakress** [comment]
Die Lösung wurde abgelehnt. Wir müssen also etwas bauen.

**Comment by annakress** [comment]
Es gab heute kein neues Feedback. Nur die Frage, ob man das Flag nicht erstmal per Default für alle Unternehmen setzen könnte anstatt umgekehrt.

**Comment by annakress** [comment]
In admin/user.rb muss noch der Parameter :mailings_enabled rein, sonst hat man nicht die Rechte zum editieren:

  permit_params :name, :organization, :email, :avatar, :mailings_enabled

**Comment by annakress** [comment]
Ich glaube, pledge_was_approved Mailing wird immer noch versandt. Die anderen Mailings scheinen soweit korrekt ausgeschlossen zu werden.

**Comment by annakress** [comment]
da #336 ,also mailings bei unterschriften, noch auf einem anderen Branch liegt, konnte ich das nicht mit testen. die sollten natürlich auch unterdrückt werden. #336 ist an sich schon getestet, und kann gerne mit diesem Branch zusammengeführt werden.

**Comment by annakress** [comment]
Nachdem ich hin  und her überlegt habe:

Die Lösung wie sie jetzt schon steht, sollte auf jeden Fall morgen deployed werden, da sie auf jeden Fall Stefanie schon mal das Leben erleichtert. Wenn #336  bis dahin nicht damit zusammengeführt werden kann, dann eben ohne #336 deployen. Wegen der pledge_approval_mailings kann ich mit Stefanie noch einmal Rücksprache halten, ob wir das nicht eher durch ihren Arbeitsflow lösen.

**Comment by KonstantinKo** [comment]
fixed, merged & deployed. Falls die flag einmal initial für viele/alle Nutzer gesetzt werden soll, kann man das auch per Konsole machen.
