### ISSUE TITLE
Erfolgreiche Versprechen / Mehr anzeigen Button

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#357]
Auf der Startseite sollten unter Erfolgreiche Versprechen ein Mehr anzeigen Button, der auf die Suchseite führt, wo dann alle erfolgreichen Versprechen gelistet werden.

**Comment by annakress** [comment]
ich habe lokal nur einen erfolgreichen pledge, aber sieht soweit gut aus. kann gerne heute deployed werden, da stefanie das morgen braucht. dann teste ich auch kurz auf production. vielen dank!

**Comment by annakress** [comment]
wenn du den button deployst, kannst du gerne die neuen übersetzungen englisch mit deployen :-)

**Comment by marcaltmann** [comment]
Oh, das war 5 Minuten zu spät. Ist jetzt deployed.

**Comment by marcaltmann** [comment]
Über die entsprechende URL lassen sich jetzt erfolgreiche, aktive und gescheiterte anzeigen:

https://www.buntundverbindlich.de/de/pledges?filter=active
https://www.buntundverbindlich.de/de/pledges?filter=successful
https://www.buntundverbindlich.de/de/pledges?filter=failed
