### ISSUE TITLE
6.4 System: Pledge ablaufen lassen

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#36]
_(6.3 war Duplikat)_
> Als System markiere ich Versprechen als „erfolgreich“ oder „nicht-erfolgreich“, sobald die Unterzeichnungs-Zeitspanne beendet ist. Der Initiator, Unterzeichner und die Redaktion erhalten automatisch eine Email-Benachrichtigung zum Status.

Erwartetes Verhalten: 
* Versprechen ist visuell als abgelaufen / erfolgreich / nicht-erfolgreich markiert
* Der Initiator, Unterzeichner und die Redaktion erhalten automatisch eine Email-Benachrichtigung zum Status.

**Comment by KonstantinKo** [comment]
Frage: Ist die eingetragene Deadline der letzte Tag, an dem noch Unterschriften gegeben werden können oder ist es der Tag, an dem der Pledge abläuft? Bin erstmal von ersterem ausgegangen.

**Comment by KonstantinKo** [comment]
Braucht noch Email-Texte:
```ruby
InitiatorMailer.pledge_successful
InitiatorMailer.pledge_failed
SignerMailer.pledge_successful
SignerMailer.pledge_failed
```

**Comment by annakress** [comment]
Zur Deadline: Hmm, verstehe jetzt den Unterschied nicht, ist doch das gleiche? Die Unterschriften können ja abgegeben werdne, bis der Pledge abläuft?

**Comment by annakress** [comment]
Emailtexte kann ich machen.

**Comment by KonstantinKo** [comment]
Nein es ist ein Unterschied von einem Tag. Wenn ein Angebot am 01.01. "abläuft" dann könnte man noch am 31.12. unterschreiben und Mitternacht beim Datumswechsel auf den 01. "läuft" es in den nächsten state

**Comment by annakress** [comment]
Ich würde es so machen, wie beim Crowdfunding, also wenn ein Versprechen am 01.01. abläuft, läuft es erst am 01.01. um 23:59 ab, und nicht am 31.12. um 23:59. Bei der Alternative mit dem 31.12. muss ein Nutzer noch den intellektuellen Aufwand aufbringen, einen Tag zurückzurechnen. Ich glaube, die erste Alternative ist leichter zu kapieren.

**Comment by KonstantinKo** [comment]
Alles klar, also kann es so bleiben wie es ist

**Comment by annakress** [comment]
Gibt`s denn eine gute Möglichkeit, das zu testen? Systemzeit in die Zukunft setzen?

**Comment by KonstantinKo** [comment]
Hmmm gute Frage. Das könnte funktionieren. Ruby tests dafür existieren ja auch schon, und Systemzeit-Test kann zwar Fehler finden, aber dann ist immernoch nicht gesagt, dass es auch mit der tatsächlichen Systemzeit des Servers  gut zusammen funktioniert (kommt ja auch auf Zeitzonen und Sommer/Winterzeit an). Im Endeffekt kann man sich wirklich nur bei nem Live-Test sicher sein.

**Comment by annakress** [comment]
Ok, live können wir ja Dummy-Pledges einstellen, zumindest solange der geschlossene September-Release läuft.

**Comment by annakress** [comment]
würde ich gerne direkt auf dem production server testen, gerne deployen.

**Comment by annakress** [comment]
Ach ja, die Emails wollte ich noch machen, deshalb Ticket wieder geöffnet.

**Comment by annakress** [comment]
localeapp-texte fertig.

**Comment by annakress** [comment]
Was noch fehlt:

- Auf den Kacheln und der Pledge-Ansicht den Pledge als erfolgreich / nicht-erfolgreich markieren. 
- Zeit-Angabe wie 0 Tage entfällt dann.
- Unterschreiben sollte dann nicht mehr möglich sein.

**Comment by marcaltmann** [comment]
Hallo @annakress, die fehlenden Punkte müssten alle umgesetzt sein, oder?

**Comment by annakress** [comment]
ok, ich teste mal.

**Comment by annakress** [comment]
Eine Sache bitte noch ergänzen:

Wenn ein Pledge die Unterzeichnerschwelle übertreten hat, sollte der Unterzeichnerbalken wieder blau sein:

![erfolg](https://cloud.githubusercontent.com/assets/2988567/18448916/432088d0-792d-11e6-84dc-6fe066bc1a22.png)

**Comment by marcaltmann** [comment]
Farbe ist gefixed. Wegen Banderole auf Kachel und Einzelansicht bitte neue Tickets aufmachen.
