### ISSUE TITLE
7.1 Sonstiges: Google Analytics

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#40]
> Einbindung von Google Analytics und ggfs. Optimizely.

**Comment by annakress** [comment]
Im head bitte eintragen:

  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-79153596-1', 'auto');
    ga('send', 'pageview');

  </script>
