### ISSUE TITLE
README aufsetzen

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#50]
Mit Installationsanweisungen

**Comment by KonstantinKo** [comment]
@annakress Tut mir leid, hab ganz vergessen, dass ich das ja noch für dich aufschreiben sollte. Schau mal rein, ob mit den Anweisungen alles funktioniert oder ob ich etwas vergessen hab.

**Comment by annakress** [comment]
@KonstantinKo Hat soweit alles funktioniert, danke! Ich schlage vor, noch den Hinweis zu Postgres hinzufügen (bestimmte Version?).

@marcaltmann Bitte noch 1-2 Zeilen zu node.js hinzufügen.
