### ISSUE TITLE
1.5 Webseitenbesucher: Melden

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#6]
> Als Webseitenbesucher kann ich Versprechen, Kommentare oder sonstigen missbräuchlichen Content an die Portal-Redaktion melden.

**Comment by KonstantinKo** [comment]
Issue ist im Oktober-Release aber Prio 1 in UAT-Dokument? Na ich habs auf jeden Fall mal gemacht. Wir haben glaub ich noch nie gesagt wie genau das melden an die Portal-Redaktion läuft. Was jetzt erstmal passiert ist, dass ein counter auf dem Pledge hoch gesetzt wird, nach dem die Redaktion im Admin-Bereich sortieren kann.
Ich denke immer eine Email zu verschicken kann sehr spammy werden, da ja jeder diesen Knopf einfach so drücken kann.

**Comment by annakress** [comment]
Für mich gut so. Muss Stefanie später entscheiden, ob sie doch lieber bespammt wird.
