### ISSUE TITLE
Darstellungsfehler drehende Kachel auf dem Mac

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#66]
Darstellungsfehler auf dem Mac mit Chrome, Opera und Safari, auf Linux funktioniert es mit Chrome und Opera.

**Comment by marcaltmann** [comment]
@KonstantinKo Kannst du mal bitte schauen, ob die Beispiele auf dieser Seite bei dir (Chrome/Opera) richtig angezeigt werden?

https://davidwalsh.name/demo/css-flip.php

Danke

**Comment by KonstantinKo** [comment]
@marcaltmann Ja alle von denen werden richtig angezeigt

**Comment by marcaltmann** [comment]
@KonstantinKo Kannst du nochmal schauen ob die Kachel jetzt funktioniert?

**Comment by KonstantinKo** [comment]
@marcaltmann Auf dem aktuellen develop stand funktioniert's noch nicht bei mir

**Comment by annakress** [comment]
da ich keinen mac habe, wäre super, wenn konstantin prüft.

**Comment by marcaltmann** [comment]
Ja, bitte auch speziell auf Safari prüfen.

**Comment by KonstantinKo** [comment]
Gut, dass du drauf hingewiesen hast. Funktioniert jetzt in allen browsern außer Safari ("der neue IE"…)

![d21-safari-tile-bug1](https://cloud.githubusercontent.com/assets/779660/17648473/7498b6a8-6217-11e6-8fc7-2a15cbd95a37.gif)

**Comment by marcaltmann** [comment]
Konstantin, schau mal bitte nochmal auf develop. Mit npm install.

**Comment by KonstantinKo** [comment]
Jau klappt auch auf Safari
