### ISSUE TITLE
Suche zeigt nicht an, wenn keine Ergebnisse gefunden werden

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#75]
Stattdessen wird dasselbe angezeigt wie wenn das Suchfeld leer ist.

**Comment by marcaltmann** [comment]
@annakress Bitte Suchverhalten nochmals überprüfen:

- Suchbegriff mit Ergebnissen
- Suchbegriff ohne Ergebnisse
- leerer Suchstring

Er liefert jetzt immer 3 Suchergebnisse auf einmal (dann 'Mehr anzeigen' klicken) zum Testen, sollte nachher wahrscheinlich erhöht werden.

**Comment by annakress** [comment]
Danke, für den Testrelease ist super so.
