### ISSUE TITLE
Versprechensformular: Design vervollständigen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#79]
Bitte nach Tinos Entwurf vervollständigen.

**Comment by marcaltmann** [comment]
Der Versprechenstext-Teil ist jetzt auch umgesetzt. Bitte einmal anschauen.

**Comment by annakress** [comment]
Bei mir sind ein Komma und ein Punkt etwas verrutscht, in Chrome, siehe Bild.

![versprechenstext](https://cloud.githubusercontent.com/assets/2988567/17649793/3ab67d64-623d-11e6-87cc-694b1d6dcb2f.png)

**Comment by annakress** [comment]
Zudem gibt es keinen Platz für Fehlermeldungen:

![versprechenstext-error](https://cloud.githubusercontent.com/assets/2988567/17649799/4bc1d888-623d-11e6-9be0-cc4b8e1e2dd0.png)

**Comment by annakress** [comment]
Außerdem falle ich immer darauf ein, dass ich da 10 sehe, bei "wie viele", aber das ist ja kein eingetragener Wert und das Feld gilt eigentlich als nicht ausgefüllt, falls ich das nicht ändere. Ich schlage vor, dass die 10 tatsächlich ein eingetragener Wert ist.

Außerdem stört es mich etwas, dass der Blauton von "was? wie viele? wer?" der gleiche wie von dem voreingetragenen Text ist, das ist etwas verwirrend. Könnten wir ausprobieren, wie es wirkt, wenn die Fragen in einem etwas helleren blau sind, so dass sie nicht ganz so ins Auge springen? Vielen Dank!

**Comment by annakress** [comment]
Mir ist noch aufgefallen, dass die Pflichtfelder nicht mit Sternchen markiert sind. Pflichtfelder hatte ich in base_pledge_form.rb festgelegt.

**Comment by marcaltmann** [comment]
Okay, müsste alles umgesetzt sein bis auf dass das Zahlen-Input-Feld noch nicht richtig funktioniert. Mache ein eigenes Ticket dafür auf.

**Comment by marcaltmann** [comment]
Siehe #135

**Comment by annakress** [comment]
Könnten wir das Feld bitte etwas größer machen, damit man den enthaltenen Text komplett sieht? Danke!

![ort](https://cloud.githubusercontent.com/assets/2988567/17896965/bbd62fb8-6952-11e6-945c-2d035275e6ec.png)

**Comment by marcaltmann** [comment]
Fixed mit rform 0.1.5
