### ISSUE TITLE
1.7 Webseitenbesucher: Multi-Language

### ISSUE THREAD

**Issue by KonstantinKo** [initiatived21/d21#8]
> Als Webseitenbesucher kann ich die Webseite in verschiedenen Sprachen nutzen, initial in Deutsch und Englisch, später auch in Arabisch etc. (Arabisch is Prio 2)

**Comment by KonstantinKo** [comment]
Done.

**Comment by annakress** [comment]
Nein, keine Eingabe in mehreren Sprachen: Wir machen es erstmal einfach: Nur das Interface wird übersetzt, wenn der Nutzer zwischen den Sprachen wechselt. Dann bleibt es ihm überlassen, ob er die Texte Deutsch oder Englisch eingibt. Die gemischte Darstellung, z.B. Interface Deutsch, Text Englisch nehmen wir in Kauf.

Bei Tags: Lasst uns erstmal mit festen Tags arbeiten, keine vom Nutzer erzeugten.

**Comment by KonstantinKo** [comment]
Noch bestehende Mehrsprachigkeits-Voraussetzungen:

- Gibt ein englischer Nutzer ein Versprechen ein "[I promis] to host a family of refugees" und dieses Versprechen wird auf der deutschen Seite angezeigt, dann wird es dem deutschen Nutzer nach deutschem Schema angezeigt ("Ich verspreche to host a family")

- Meldet sich ein Benutzer über die englische Seite an, bekommt dieser trotzdem deutsche Emails

Evtl. noch andere Dinge, am besten sollten wir mal einen englischen Tester mit dazu holen.

**Comment by KonstantinKo** [comment]
Habe meine obigen beiden Punkte in PR #299 gefixt. Bevor man das auf production benutzt braucht es natürlich einige Übersetzungen. Es lohnt sich aber schon vorher zu mergen, um später größere merge Konflikte zu vermeiden

**Comment by annakress** [comment]
ok, lasst uns mergen, falls das für di / also morgen realistisch ist. sprachregler bleibt ja erstmal deaktiviert. da ich keine übersetzungen erhalten habe, werde ich stefanie mitteilen, dass die übersetzte seite für den launch nicht machbar ist.
