### ISSUE TITLE
Versprechensformular: Bereich Nutzerdaten

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#80]
Bereich Ihre Daten für Ihr Nutzerkonto: Formularfelder fehlen, Beschriftungen fehlen, Teil des Textes ganz oben (Einlogghinweis) fehlt: Bitte mit Cacoo abgleichen

Kann auch zusammen mit dem Test Case Nutzerdaten editieren gemacht werden.

**Comment by KonstantinKo** [comment]
Done & merged.
Bitte nochmal nach dem styling schauen.

**Comment by marcaltmann** [comment]
@KonstantinKo Styling sieht für mich okay aus.

**Comment by KonstantinKo** [comment]
Ehrlich? Auch der Button?

**Comment by marcaltmann** [comment]
Ich weiß nicht was du meinst. Kannst du mir einen Screenshot schicken?

**Comment by KonstantinKo** [comment]
<img width="1016" alt="screen shot 2016-08-27 at 17 29 26" src="https://cloud.githubusercontent.com/assets/779660/18028311/dca860fe-6c7b-11e6-9a0c-669cbfdd2736.png">

**Comment by marcaltmann** [comment]
Profil hatte ich ganz vergessen...
