### ISSUE TITLE
Versprechensansichtsseite: Design

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#81]
Bitte Design nach Tinos Entwurf ergänzen.

**Comment by annakress** [comment]
hallo marc, ist der code schon gemerged? ich seh irgendwie keinen unterschied. danke!

**Comment by marcaltmann** [comment]
Ja, der obere Teil der Pledge-Einzelansicht sollte anders aussehen. Abstände, Schriftgrößen, graue Linie zwischen INITIATOR und Pledge-Text usw.

**Comment by annakress** [comment]
Danke!
Was mir noch auffällt, ist dass der Kreis mit den Tagen nicht an dem Balken mit den Unterstützern ausgerichtet ist. Genauso müsste der Text "0% vom Ziel" an "Endet am" ausgerichtet werden. Damit es etwas ausgewogener aussieht.

**Comment by annakress** [comment]
Und wenn es kein Bild oder weiteren Text zu dem Pledge gibt, sehe ich eine Riesenlücke zwischen "Veröffentlicht am 06.08.2016 um 18:56 Uhr" und "Neuigkeiten".
