### ISSUE TITLE
Versprechensansichtseite: Tags

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#82]
Bitte Tags dynamisch einbinden.

**Comment by marcaltmann** [comment]
Schwierig...

**Comment by annakress** [comment]
Sobald ich ein Versprechen über die Kachel anklicke, um zur Versprechensansicht zu kommen, bekomme ich: 

ReactOnRails::PrerenderError at /de/pledges/17
ERROR in SERVER PRERENDERING
when prerendering PledgeView with props: {"pledge":{"id":17,"title":"bla blob","content":"blab blob","amount":11,"who":"bla blob","requirement":"bla blob","location":"Berlin","deadline":"2016-11-11","description":"","signatures_count":0,"aasm_state":"initialized","created_at":"2016-08-16T15:10:07.208Z","user_id":12,"image":{"url":null},"initiator":{"id":12,"name":"bla blob","organization":null,"avatar":{"url":null},"confirmed":true},"tags":[{"id":2,"name":"books","color":null}]},"forms":{"signPledgeForm":{"action":"/de/pledges/17/signatures","authToken":"+3/DYG4p4HfT9mLa0yNKK+gIePDXdOwO1ecsFNi/v3AvuyGSHsiME3M2YcLTCKSuyYthJRjsZuYLy49l6DDVfw==","model":"signature"},"updateForm":{"action":"/de/pledges/17/updates","authToken":"JOoLYg0l7Fytk+TmRsvyj5o412F4NmywZYg7RI4KAMLwLumQfcSAOA1T5/5G4BwKu7vOtLeu5li7pJg1voVqzQ==","model":"update"},"questionForm":{"action":"/de/pledges/17/comments","authToken":"msAhBhS+ST+T8hWn/ib36Ep3DeI7YHmeiyb7Yy6cyv5OBMP0ZF8lWzMyFr/+DRlta/QUN/T483ZVClgSHhOg8Q==","model":"comment"},"answerForm":{"action":"/de/comments/:id","authToken":"+rBXObfW4ygEuvwp5u1QoSAqmDKIPYhpy5KljsdAy20udLXLxzePTKR6/zHmxr4kAamB50elAoEVvgb/98+hYg==","model":"comment","method":"PATCH"}},"user":{"id":12,"name":"bla blob","organization":null,"avatar":{"url":null},"confirmed":true},"signatures":[],"updates":[],"comments":[],"locale":"de"}
js_code was:
(function() {
  var railsContext = {"href":"http://localhost:3000/de/pledges/17","location":"/de/pledges/17","scheme":"http","host":"localhost","port":3000,"pathname":"/de/pledges/17","search":null,"i18nLocale":"de","i18nDefaultLocale":"de","httpAcceptLanguage":"de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,pt;q=0.2,fr;q=0.2,ru;q=0.2","serverSide":true};

  var props = {"pledge":{"id":17,"title":"bla blob","content":"blab blob","amount":11,"who":"bla blob","requirement":"bla blob","location":"Berlin","deadline":"2016-11-11","description":"","signatures_count":0,"aasm_state":"initialized","created_at":"2016-08-16T15:10:07.208Z","user_id":12,"image":{"url":null},"initiator":{"id":12,"name":"bla blob","organization":null,"avatar":{"url":null},"confirmed":true},"tags":[{"id":2,"name":"books","color":null}]},"forms":{"signPledgeForm":{"action":"/de/pledges/17/signatures","authToken":"+3/DYG4p4HfT9mLa0yNKK+gIePDXdOwO1ecsFNi/v3AvuyGSHsiME3M2YcLTCKSuyYthJRjsZuYLy49l6DDVfw==","model":"signature"},"updateForm":{"action":"/de/pledges/17/updates","authToken":"JOoLYg0l7Fytk+TmRsvyj5o412F4NmywZYg7RI4KAMLwLumQfcSAOA1T5/5G4BwKu7vOtLeu5li7pJg1voVqzQ==","model":"update"},"questionForm":{"action":"/de/pledges/17/comments","authToken":"msAhBhS+ST+T8hWn/ib36Ep3DeI7YHmeiyb7Yy6cyv5OBMP0ZF8lWzMyFr/+DRlta/QUN/T483ZVClgSHhOg8Q==","model":"comment"},"answerForm":{"action":"/de/comments/:id","authToken":"+rBXObfW4ygEuvwp5u1QoSAqmDKIPYhpy5KljsdAy20udLXLxzePTKR6/zHmxr4kAamB50elAoEVvgb/98+hYg==","model":"comment","method":"PATCH"}},"user":{"id":12,"name":"bla blob","organization":null,"avatar":{"url":null},"confirmed":true},"signatures":[],"updates":[],"comments":[],"locale":"de"};
  return ReactOnRails.serverRenderReactComponent({
    name: 'PledgeView',
    domNodeId: 'PledgeView-react-component-bed7ce1e-842a-4ed8-9ede-752be20522ae',
    props: props,
    trace: true,
    railsContext: railsContext
  });
})()

console messages:

<script>
console.log.apply(console, ["[SERVER] RENDERED PledgeView to dom node with id: PledgeView-react-component-bed7ce1e-842a-4ed8-9ede-752be20522ae with railsContext:","{\"href\":\"http://localhost:3000/de/pledges/17\",\"location\":\"/de/pledges/17\",\"scheme\":\"http\",\"host\":\"localhost\",\"port\":3000,\"pathname\":\"/de/pledges/17\",\"search\":null,\"i18nLocale\":\"de\",\"i18nDefaultLocale\":\"de\",\"httpAcceptLanguage\":\"de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,pt;q=0.2,fr;q=0.2,ru;q=0.2\",\"serverSide\":true}"]);
console.log.apply(console, ["[SERVER] will dispatch","{\"type\":\"ADD_ENTITIES\",\"entities\":{\"pledges\":{\"17\":{\"id\":17,\"title\":\"bla blob\",\"content\":\"blab blob\",\"amount\":11,\"who\":\"bla blob\",\"requirement\":\"bla blob\",\"location\":\"Berlin\",\"deadline\":\"2016-11-11\",\"description\":\"\",\"signatures_count\":0,\"aasm_state\":\"initialized\",\"created_at\":\"2016-08-16T15:10:07.208Z\",\"user_id\":12,\"image\":{\"url\":null},\"initiator\":12,\"tags\":[2]}},\"users\":{\"12\":{\"id\":12,\"name\":\"bla blob\",\"organization\":null,\"avatar\":{\"url\":null},\"confirmed\":true}},\"tags\":{\"2\":{\"id\":2,\"name\":\"books\",\"color\":null}}}}"]);
console.log.apply(console, ["[SERVER] state after dispatch","{\"pledges\":{\"7\":{\"id\":7,\"title\":\"Fahrradfahren lernen\",\"content\":\"zehn Frauen und Kindern aus Flüchtlingsfamilien Fahrradfahren beizubringen\",\"amount\":10,\"who\":\"Menschen\",\"requirement\":\"bereit sind, ein fahrtüchtiges Fahrrad zu spenden\",\"location\":\"Hamburg\",\"deadline\":\"2016-08-03\",\"description\":null,\"signatures_count\":21,\"aasm_state\":\"successful\",\"created_at\":\"2016-08-06T16:56:12.929Z\",\"user_id\":2,\"image\":{\"url\":null},\"initiator\":2,\"tags\":[]},\"17\":{\"id\":17,\"title\":\"bla blob\",\"content\":\"blab blob\",\"amount\":11,\"who\":\"bla blob\",\"requirement\":\"bla blob\",\"location\":\"Berlin\",\"deadline\":\"2016-11-11\",\"description\":\"\",\"signatures_count\":0,\"aasm_state\":\"initialized\",\"created_at\":\"2016-08-16T15:10:07.208Z\",\"user_id\":12,\"image\":{\"url\":null},\"initiator\":12,\"tags\":[2],\"updated_at\":\"2016-08-16T15:10:07.208Z\"}},\"tags\":[null,null,{\"id\":2,\"name\":\"books\",\"color\":null}],\"ui\":{\"searchResultsLoading\":false,\"sessionPopupVisible\":false},\"isSubmitting\":{},\"imageInputs\":{\"avatar\":{\"imageState\":0,\"originalImage\":null,\"originalImageWidth\":0,\"originalImageHeight\":0,\"crop\":{},\"croppedImageUrl\":\"\"},\"image\":{\"imageState\":0,\"originalImage\":null,\"originalImageWidth\":0,\"originalImageHeight\":0,\"crop\":{},\"croppedImageUrl\":\"\"}},\"users\":{\"2\":{\"id\":2,\"name\":\"Max Mustermann\",\"organization\":null,\"avatar\":{\"url\":null},\"confirmed\":false},\"12\":{\"id\":12,\"name\":\"bla blob\",\"organization\":null,\"avatar\":{\"url\":null},\"confirmed\":true}},\"currentUser\":{\"id\":12,\"name\":\"bla blob\",\"organization\":null,\"avatar\":{\"url\":null},\"confirmed\":true},\"authToken\":\"ipdJcPhJ+kSsRZDNmKR+ZU0/TPEMf/thJfZdoj2cMIFeU6uCiKiWIAyFk9WYj5DgbLxVJMPncYn72v7TDRNajg==\",\"SignInFormObject\":{},\"PledgeWithInitiatorFormObject\":{\"title\":null,\"content\":null,\"amount\":null,\"who\":null,\"requirement\":null,\"location\":null,\"deadline\":null,\"image\":{\"image\":{\"url\":null}},\"description\":null,\"tag_ids\":[],\"initiator\":{\"name\":null,\"organization\":null,\"avatar\":\"\",\"email\":\"\",\"password\":null}}}"]);
console.error.apply(console, ["[SERVER] Exception in rendering!"]);
console.error.apply(console, ["[SERVER] message: Cannot call method 'map' of undefined"]);
console.error.apply(console, ["[SERVER] stack: TypeError: Cannot call method 'map' of undefined\n    at TagList (<eval>:56620:17)\n    at ReactCompositeComponentMixin._constructComponentWithoutOwner (<eval>:22870:28)\n    at ReactCompositeComponentMixin._constructComponent (<eval>:22838:22)\n    at ReactCompositeComponentMixin.mountComponent (<eval>:22757:22)\n    at Object.ReactReconciler.mountComponent (<eval>:14658:36)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (<eval>:22028:45)\n    at ReactDOMComponent.Mixin._createContentMarkup (<eval>:17688:33)\n    at ReactDOMComponent.Mixin.mountComponent (<eval>:17570:30)\n    at Object.ReactReconciler.mountComponent (<eval>:14658:36)\n    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (<eval>:22028:45)"]);

**Comment by annakress** [comment]
Und manche der Kacheln zeigen keine Tags an:

![tags](https://cloud.githubusercontent.com/assets/2988567/17704632/f0f22e04-63d5-11e6-8091-2d5e585f0763.png)

**Comment by KonstantinKo** [comment]
Sorry, zu eilig gepusht. Aber der Fehler mit dem undefined Namen muss eigentlich an deinen Daten liegen. Dann musst du da einen unbenamten tag in deiner Datenbank haben. kannst bitte versuchen ob das immer noch passiert wenn du neu seedest?

**Comment by annakress** [comment]
Beide Probleme wurden mit dem  neuen Code behoben.
