### ISSUE TITLE
Vorschau Versprechen: Buttons/Texte

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#84]
Zurück/Bearbeiten-Button fehlt (vgl. Mockup), falls ich von der Vorschau zurück zum Formular will.

Kursiver Text "Veröffentlicht am ...." unter dem Pledge-Bild sollte nicht angezeigt werden, da noch nicht veröffentlicht.

Tags aus dem Formular werden nicht korrekt übernommen, die sind wahrscheinlich ncoh nicht dynamisch eingebunden.

Wenn man Versprehen and die Redaktion schicken will: Text zum Zustimmen zu den Nutzungsbedingungen fehlt komplett (vgl. Mockup).

**Comment by marcaltmann** [comment]
@annakress Schau mal bitte, so siehts im Moment aus. Löschen-Button fehlt, ist aber auch schwer unterzubringen.

![vorschau](https://cloud.githubusercontent.com/assets/2727647/17850421/6878d492-685d-11e6-9a51-7463e451dfae.png)

**Comment by annakress** [comment]
sieht gut aus!

**Comment by annakress** [comment]
wir können den löschen button erstmal weglassen, aber im profil müsste man entwürfe löschen können (gibt ein anderes ticket dafür.)
