### ISSUE TITLE
Vorschau Versprechen: Design

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#85]
Die Texte rechts, z.B. "sie müssen noch ihre Adresse bestätigen, bevor sie absenden können bzw. hier können sie das versprechen an die redaktion absenden" sollten prominenter/schöner gestylt werden, z.B. in box mit rotem rand.

**Comment by marcaltmann** [comment]
Ich habe mal eine blaue Box für die Neuigkeiten gestylt. Siehe Bild.
![neuigkeiten](https://cloud.githubusercontent.com/assets/2727647/17625664/1bf383a2-60aa-11e6-8b1c-742af27a6fe1.png)

**Comment by annakress** [comment]
sieht gut aus!
