### ISSUE TITLE
Fehlerseite statt Serverfehler

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#86]
Wir benötigen generell eine Seite, die angezeigt wird, wenn Serverfehler passieren.

Z.B. : Wenn der Nutzer eine ungültige url eingibt: "Diese Seite existiert nicht."

**Comment by KonstantinKo** [comment]
"Seite nicht gefunden"-Seite wird nun angezeigt, wenn ein angefragtes Objekt nicht gefunden wird (/de/pledges/99999) und wenn keine Bereichtigung für eine Seite existiert.

Tatsächliche Serverfehler enden immernoch auf der standard-500er-Seite. Hierfür braucht es auch etwas mehr arbeit: Eine statische 500.html im public Ordner die am besten auch keine oder nicht viele Links enthält weil es ja sein kann, dass es Seitenweite Probleme gibt. Ein Suchformular wäre daher auch ungünstig. Da müsste also ein klein bisschen was umdesigned werden.

**Comment by annakress** [comment]
ok, ich schiebs wegen der 500-seite wieder ins backlog.

**Comment by marcaltmann** [comment]
Ich hab das Design der 500er-Seite mal leicht an unsere Seite angepasst und mit einem etwas blöden Spruch versehen, siehe Bild.

@annakress Kannst du sagen, was da rein soll (also Text, Links usw.) und wie das ganze aussehen soll?

![500error](https://cloud.githubusercontent.com/assets/2727647/18750207/7e75fff0-80da-11e6-8953-ced57e8652a4.png)

**Comment by annakress** [comment]
Also für den Anfang können wir das so lassen.
