### ISSUE TITLE
Entwürfe von Versprechen löschen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#87]
Es gibt keine Möglichkeit, einen gespeicherten Versprechens-Entwurf zu Löschen.
Ich schlage im Profil neben dem Bearbeiten Button auch einen Löschen Button vor.

**Comment by marcaltmann** [comment]
Das funktioniert jetzt, allerdings werden versprechen ohne Rückmeldung gelöscht. Ich schlage vor, hier ein einfaches "Sind Sie sicher?"-Fenster einzubauen.
Sollen aktive Versprechen auch gelöscht werden können? Ist es in diesem Fall sinnvoll, einen speziellen Hinweis auszugeben, dass das Versprechen aktiv ist?

**Comment by annakress** [comment]
Ja, Rückfrage wäre sinnvoll, auch besonderer Hinweis bei aktiven Versprechen. Würde ich auch erlauben, dass man die aktiven löschen kann, wüßte nicht, warum man den Initiator da einschränken sollte.

**Comment by annakress** [comment]
Löschen funktioniert, Rückfrage noch offen.
