### ISSUE TITLE
FAQ einpflegen

### ISSUE THREAD

**Issue by annakress** [initiatived21/d21#92]

**Comment by annakress** [comment]
Jetzt fehlt noch das Markup.

(Übersetzungen kriegen wir von Stefanie.)

**Comment by annakress** [comment]
Ich denke, die bisherige Lösung für FAQ/Localeapp, die sich die Fragen iterativ holt, hat das Problem, dass meine Fragen/Antworten zum Teil mehrere Paragrafen enthalten und Listen. Die bisherige Lösung besteht doch nur aus Fragesatz/Antwortsatz, oder? Deshalb ist das Stylen mit der bisherigen Lösung eher schwierig. Siehe auch FAQ Dokument auf Basecamp.

**Comment by marcaltmann** [comment]
Vielleicht können wir die Texte mit Markdown in Localeapp speichern, das ist vielleicht etwas einfacher als direktes HTML.

**Comment by marcaltmann** [comment]
@annakress Ich habs jetzt über die Markup-Sprache Markdown gemacht. Ein Beispiel habe ich auch gesetzt, den ersten FAQ-Punkt. Schau dir bitte mal an, also einmal die FAQ-Seite und den Text auf Locale, ob es so für dich funktioniert.

**Comment by marcaltmann** [comment]
Mir ist noch aufgefallen, dass die Zeilen immer noch recht lang sind, obwohl nur 2/3 der Seite genutzt werden. Optimal sollen so 65 Zeichen sein, jetzt sind es 95. Das ist dann nur noch die Hälfte der Seite. Daher kann man es eigentlich auch zweispaltig machen, siehe Screenshot.
![faq](https://cloud.githubusercontent.com/assets/2727647/17812163/29d079cc-6626-11e6-9122-b7e655a26e9f.png)

**Comment by annakress** [comment]
Danke, so geht`s.
Lass uns gerne erstmal einspaltig lassen, zweispaltig finde ich nicht so schön.
Wir werden ja auch noch andere Textseiten haben, wie "Über uns" usw., da sollten wir einen einspaltigen Ansatz haben.
