### ISSUE TITLE
Hauptmenü aktiven Menüpunkt anzeigen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#94]
Im Hauptmenü sollte der aktive Menüpunkt immer mit blauem Hintergrund angezeigt werden.

Der aktive Menüpunkt muss also dynamisch die richtige CSS-Klasse "c-primary-nav__item--active" (siehe views/layouts/partials/_header.erb) zugewiesen bekommen.

**Comment by annakress** [comment]
Nachdem ich diverse Sachen ausprobiert habe, die ich im Netz gefunden habe, muss ich hier passen...
"Start" ist nicht als Link angelegt (sollte aber auch ein Link sein), und hat deshalb anderes CSS als die anderen Navilinks.

Theoretisch sollte es mit <% if current_page?(home_path) %> c-primary-nav__item--active" gehen, aber ich komme nicht mit dem CSS zurecht.
