### ISSUE TITLE
Tooltips für Formulare bauen

### ISSUE THREAD

**Issue by marcaltmann** [initiatived21/d21#95]

**Comment by marcaltmann** [comment]
Ich habe einen Tooltip zum Testen ins Pledge-Formular eingebaut (neben dem Ort-Feld). @annakress kannst du bitte schauen, für welche Felder in welchen Formularen wir genau Tooltips brauchen?

**Comment by annakress** [comment]
sieht gut aus, ja mach ich.

**Comment by annakress** [comment]
für versprechens-formular und unterzeichnen-formular sind die tooltipps hier:

https://3.basecamp.com/3302998/buckets/570303/uploads/203785529

**Comment by annakress** [comment]
Hallo Marc,

Du hast in dem Versprechens-Formular vermutlich einen anderen Pfad zu den Übersetzungen eingefügt?

Jetzt ist es react_form.pledge.*
Davor (und zum Teil noch in den englischen Übersetzungen) war es PledgeForm.*

Hat das einen bestimmten Grund? Wie sollen wir das vereinheitlichen?

VG Anna

**Comment by marcaltmann** [comment]
In "react_form" stehen die ganzen formularspezifischen Sachen, Platzhalter, Labels usw., in PledgeForm der ganze Rest. Die Trennung ist gewollt, weil er die Struktur für die formularspezifischen Sachen automatisch anhand des Models und der Attribute erzeugt wird.
Außerdem hat Konstantin gerade react_form in rform umbenannt, da er am Wochenende das ganze als npm-Modul ausgelagert hat.

**Comment by annakress** [comment]
ok, danke, dann füg ich mal die restlichen tooltipps hinzu.

**Comment by marcaltmann** [comment]
Okay, baue ich heute noch ein.

**Comment by annakress** [comment]
Ach so, kann ich aber auch versuchen :-) Ich glaube für Dich gibt es noch wichtigere Tickets.

**Comment by marcaltmann** [comment]
Kannst du gerne machen aber für das unterzeichnen formular muss ich das Markup wohl noch ändern danach.

**Comment by annakress** [comment]
ich habe die tooltips eingebaut, aber es muss noch gemacht werden:

- in beiden formularen das design wieder geraderücken
- irgendwo muss wohl der pfad von de.react_form nach de.rform für die Übersetzungen korrigiert werden
